(function(){var a=function(c,a){return function(){return c.apply(a,arguments)}},d=Object.prototype.hasOwnProperty,c=function(){this.patch_apply_with_offsets=a(this.patch_apply_with_offsets,this);this.transform_object_diff=a(this.transform_object_diff,this);this.transform_list_diff=a(this.transform_list_diff,this);this.apply_object_diff_with_offsets=a(this.apply_object_diff_with_offsets,this);this.apply_object_diff=a(this.apply_object_diff,this);this.apply_list_diff=a(this.apply_list_diff,this);this.diff=
a(this.diff,this);this.object_diff=a(this.object_diff,this);this.list_diff=a(this.list_diff,this);this._common_suffix=a(this._common_suffix,this);this._common_prefix=a(this._common_prefix,this);this.object_equals=a(this.object_equals,this);this.list_equals=a(this.list_equals,this);this.equals=a(this.equals,this);this.deepCopy=a(this.deepCopy,this);this.typeOf=a(this.typeOf,this);this.entries=a(this.entries,this)};c.dmp=new diff_match_patch;c.prototype.entries=function(c){var a,b;b=0;for(a in c)d.call(c,
a)&&b++;return b};c.prototype.typeOf=function(c){var a;a=typeof c;"object"===a&&(c?"number"===typeof c.length&&("function"===typeof c.splice&&!c.propertyIsEnumerable("length"))&&(a="array"):a="null");return a};c.prototype.deepCopy=function(c){var a,b,e;if("[object Array]"===Object.prototype.toString.call(c)){b=[];a=0;for(e=c.length;0<=e?a<e:a>e;0<=e?a++:a--)b[a]=arguments.callee(c[a]);return b}if("object"===typeof c){b={};for(a in c)b[a]=arguments.callee(c[a]);return b}return c};c.prototype.equals=
function(c,a){var b,e;b=this.typeOf(c);e=this.typeOf(a);return"boolean"===b&&"number"===e?Number(c)===a:"number"===b&&"boolean"===e?Number(a)===c:b!==e?!1:"array"===b?this.list_equals(c,a):"object"===b?this.object_equals(c,a):c===a};c.prototype.list_equals=function(c,a){var b,e;b=c.length;if(b!==a.length)return!1;for(e=0;0<=b?e<b:e>b;0<=b?e++:e--)if(!this.equals(c[e],a[e]))return!1;return!0};c.prototype.object_equals=function(c,a){for(var b in c)if(d.call(c,b)&&(!(b in a)||!this.equals(c[b],a[b])))return!1;
for(b in a)if(d.call(a,b)&&!(b in c))return!1;return!0};c.prototype._common_prefix=function(c,a){var b,e;e=Math.min(c.length,a.length);for(b=0;0<=e?b<e:b>e;0<=e?b++:b--)if(!this.equals(c[b],a[b]))return b;return e};c.prototype._common_suffix=function(c,a){var b,e,h,d;e=c.length;h=a.length;d=Math.min(c.length,a.length);if(0===d)return 0;for(b=0;0<=d?b<d:b>d;0<=d?b++:b--)if(!this.equals(c[e-b-1],a[h-b-1]))return b;return d};c.prototype.list_diff=function(c,a){var b,e,d,i,j,k;b={};d=c.length;i=a.length;
k=this._common_prefix(c,a);e=this._common_suffix(c,a);c=c.slice(k,d-e);a=a.slice(k,i-e);d=c.length;i=a.length;j=Math.max(d,i);for(e=0;0<=j?e<=j:e>=j;0<=j?e++:e--)e<d&&e<i?this.equals(c[e],a[e])||(b[e+k]=this.diff(c[e],a[e])):e<d?b[e+k]={o:"-"}:e<i&&(b[e+k]={o:"+",v:a[e]});return b};c.prototype.object_diff=function(c,a){var b,e;b={};if(null==c||null==a)return{};for(e in c)d.call(c,e)&&(e in a?this.equals(c[e],a[e])||(b[e]=this.diff(c[e],a[e])):b[e]={o:"-"});for(e in a)d.call(a,e)&&!(e in c)&&null!=
a[e]&&(b[e]={o:"+",v:a[e]});return b};c.prototype.diff=function(a,d){var b;if(this.equals(a,d))return{};b=this.typeOf(a);if(b!==this.typeOf(d))return{o:"r",v:d};switch(b){case "boolean":return{o:"r",v:d};case "number":return{o:"r",v:d};case "array":return{o:"r",v:d};case "object":return{o:"O",v:this.object_diff(a,d)};case "string":if(b=c.dmp.diff_main(a,d),2<b.length&&c.dmp.diff_cleanupEfficiency(b),0<b.length)return{o:"d",v:c.dmp.diff_toDelta(b)}}return{}};c.prototype.apply_list_diff=function(a,
g){var b,e,h,i,j,k,l,n;k=this.deepCopy(a);i=[];b=[];for(j in g)d.call(g,j)&&(i.push(j),i.sort());j=0;for(n=i.length;j<n;j++){h=i[j];e=g[h];for(var r=void 0,s=void 0,p=void 0,p=[],r=0,s=b.length;r<s;r++)l=b[r],l<=h&&p.push(l);l=p.length;h-=l;switch(e.o){case "+":[].splice.apply(k,[h,h-h+1].concat(e=e.v));e;break;case "-":[].splice.apply(k,[h,h-h+1].concat(e=[]));e;b[b.length]=h;break;case "r":k[h]=e.v;break;case "I":k[h]+=e.v;break;case "L":k[h]=this.apply_list_diff(k[h],e.v);break;case "O":k[h]=this.apply_object_diff(k[h],
e.v);break;case "d":e=c.dmp.diff_fromDelta(k[h],e.v),e=c.dmp.patch_make(k[h],e),e=c.dmp.patch_apply(e,k[h]),k[h]=e[0]}}return k};c.prototype.apply_object_diff=function(a,g){var b,e,h;h=this.deepCopy(a);for(e in g)if(d.call(g,e))switch(b=g[e],b.o){case "+":h[e]=b.v;break;case "-":delete h[e];break;case "r":h[e]=b.v;break;case "I":h[e]+=b.v;break;case "L":h[e]=this.apply_list_diff(h[e],b.v);break;case "O":h[e]=this.apply_object_diff(h[e],b.v);break;case "d":b=c.dmp.diff_fromDelta(h[e],b.v),b=c.dmp.patch_make(h[e],
b),b=c.dmp.patch_apply(b,h[e]),h[e]=b[0]}return h};c.prototype.apply_object_diff_with_offsets=function(a,g,b,e){var h,i,a=this.deepCopy(a);for(i in g)if(d.call(g,i))switch(h=g[i],h.o){case "+":a[i]=h.v;break;case "-":delete a[i];break;case "r":a[i]=h.v;break;case "I":a[i]+=h.v;break;case "L":a[i]=this.apply_list_diff(a[i],h.v);break;case "O":a[i]=this.apply_object_diff(a[i],h.v);break;case "d":h=c.dmp.diff_fromDelta(a[i],h.v),h=c.dmp.patch_make(a[i],h),i===b?a[i]=this.patch_apply_with_offsets(h,a[i],
e):(h=c.dmp.patch_apply(h,a[i]),a[i]=h[0])}return a};c.prototype.transform_list_diff=function(a,c,b){var e,h,i,j,k,l;e={};i=[];h=[];for(k in c)d.call(c,k)&&(j=c[k],"+"===j.o&&i.push(k),"-"===j.o&&h.push(k));for(k in a)if(d.call(a,k)){j=a[k];for(var n=void 0,r=void 0,s=void 0,s=[],n=0,r=i.length;n<r;n++)l=i[n],l<=k&&s.push(l);s=r=n=void 0;s=[];n=0;for(r=h.length;n<r;n++)l=h[n],l<=k&&s.push(l);k=k+1-1;l=String(k);e[l]=j;k in c&&!("+"===j.o&&"+"===c.index.o)&&("-"===j.o&&"-"===c.index.o?delete e[l]:
(j=this.transform_object_diff({sindex:j},{sindex:c.index},b),e[l]=j[l]))}return e};c.prototype.transform_object_diff=function(a,g,b){var e,h,i,j;h=this.deepCopy(a);for(j in a)if(d.call(a,j)&&(e=a[j],j in g))return a=b[j],g=g[j],"+"===e.o&&"+"===g.o?this.equals(e.v,g.v)?delete h[j]:h[j]=this.diff(g.v,e.v):"-"===e.o&&"-"===g.o?delete h[j]:"-"===g.o&&("O"===(i=e.o)||"L"===i||"I"===i||"d"===i)?(h[j]={o:"+"},"O"===e.o?h[j].v=this.apply_object_diff(a,e.v):"L"===e.o?h[j].v=this.apply_list_diff(a,e.v):"I"===
e.o?h[j].v=a+e.v:"d"===e.o?(e=c.dmp.diff_fromDelta(a,e.v),e=c.dmp.patch_make(a,e),a=c.dmp.patch_apply(e,a),h[j].v=a[0]):delete h[j]):"O"===e.o&&"O"===g.o?h[j]={o:"O",v:this.transform_object_diff(e.v,g.v,a)}:"L"===e.o&&"L"===g.o?h[j]={o:"O",v:this.transform_list_diff(e.v,g.v,a)}:"d"===e.o&&"d"===g.o&&(delete h[j],e=c.dmp.patch_make(a,c.dmp.diff_fromDelta(a,e.v)),i=c.dmp.patch_make(a,c.dmp.diff_fromDelta(a,g.v)),a=c.dmp.patch_apply(i,a)[0],e=c.dmp.patch_apply(e,a)[0],e!==a&&(e=c.dmp.diff_main(a,e),
2<e.length&&c.dmp.diff_cleanupEfficiency(e),0<e.length&&(h[j]={o:"d",v:c.dmp.diff_toDelta(e)}))),h};c.prototype.patch_apply_with_offsets=function(){};c.prototype.patch_apply_with_offsets=function(a,d,b){if(0==a.length)return d;var a=c.dmp.patch_deepCopy(a),e=c.dmp.patch_addPadding(a),d=e+d+e;c.dmp.patch_splitMax(a);for(var h=0,i=0;i<a.length;i++){var j=a[i].start2+h,k=c.dmp.diff_text1(a[i].diffs),l,n=-1;if(k.length>c.dmp.Match_MaxBits){if(l=c.dmp.match_main(d,k.substring(0,c.dmp.Match_MaxBits),j),
-1!=l&&(n=c.dmp.match_main(d,k.substring(k.length-c.dmp.Match_MaxBits),j+k.length-c.dmp.Match_MaxBits),-1==n||l>=n))l=-1}else l=c.dmp.match_main(d,k,j);if(-1==l)h-=a[i].length2-a[i].length1;else if(h=l-j,j=-1==n?d.substring(l,l+k.length):d.substring(l,n+c.dmp.Match_MaxBits),j=c.dmp.diff_main(k,j,!1),!(k.length>c.dmp.Match_MaxBits&&c.dmp.diff_levenshtein(j)/k.length>c.dmp.Patch_DeleteThreshold))for(var k=0,r,n=0;n<a[i].diffs.length;n++){var s=a[i].diffs[n];s[0]!==DIFF_EQUAL&&(r=c.dmp.diff_xIndex(j,
k));if(s[0]===DIFF_INSERT)for(var d=d.substring(0,l+r)+s[1]+d.substring(l+r),p=0;p<b.length;p++)b[p]+e.length>l+r&&(b[p]+=s[1].length);else if(s[0]===DIFF_DELETE)for(var m=l+r,q=l+c.dmp.diff_xIndex(j,k+s[1].length),d=d.substring(0,m)+d.substring(q),p=0;p<b.length;p++)b[p]+e.length>m&&(b[p]=b[p]+e.length<q?m-e.length:b[p]-(q-m));s[0]!==DIFF_DELETE&&(k+=s[1].length)}}return d=d.substring(e.length,d.length-e.length)};window.jsondiff=c}).call(this);function diff_match_patch(){this.Diff_Timeout=1;this.Diff_EditCost=4;this.Match_Threshold=0.5;this.Match_Distance=1E3;this.Patch_DeleteThreshold=0.5;this.Patch_Margin=4;this.Match_MaxBits=32}var DIFF_DELETE=-1,DIFF_INSERT=1,DIFF_EQUAL=0;
diff_match_patch.prototype.diff_main=function(a,d,c,f){"undefined"==typeof f&&(f=0>=this.Diff_Timeout?Number.MAX_VALUE:(new Date).getTime()+1E3*this.Diff_Timeout);if(null==a||null==d)throw Error("Null input. (diff_main)");if(a==d)return a?[[DIFF_EQUAL,a]]:[];"undefined"==typeof c&&(c=!0);var g=c,b=this.diff_commonPrefix(a,d),c=a.substring(0,b),a=a.substring(b),d=d.substring(b),b=this.diff_commonSuffix(a,d),e=a.substring(a.length-b),a=a.substring(0,a.length-b),d=d.substring(0,d.length-b),a=this.diff_compute_(a,
d,g,f);c&&a.unshift([DIFF_EQUAL,c]);e&&a.push([DIFF_EQUAL,e]);this.diff_cleanupMerge(a);return a};
diff_match_patch.prototype.diff_compute_=function(a,d,c,f){if(!a)return[[DIFF_INSERT,d]];if(!d)return[[DIFF_DELETE,a]];var g=a.length>d.length?a:d,b=a.length>d.length?d:a,e=g.indexOf(b);return-1!=e?(c=[[DIFF_INSERT,g.substring(0,e)],[DIFF_EQUAL,b],[DIFF_INSERT,g.substring(e+b.length)]],a.length>d.length&&(c[0][0]=c[2][0]=DIFF_DELETE),c):1==b.length?[[DIFF_DELETE,a],[DIFF_INSERT,d]]:(g=this.diff_halfMatch_(a,d))?(d=g[1],b=g[3],a=g[4],g=this.diff_main(g[0],g[2],c,f),c=this.diff_main(d,b,c,f),g.concat([[DIFF_EQUAL,
a]],c)):c&&100<a.length&&100<d.length?this.diff_lineMode_(a,d,f):this.diff_bisect_(a,d,f)};
diff_match_patch.prototype.diff_lineMode_=function(a,d,c){var f=this.diff_linesToChars_(a,d),a=f.chars1,d=f.chars2,f=f.lineArray,a=this.diff_main(a,d,!1,c);this.diff_charsToLines_(a,f);this.diff_cleanupSemantic(a);a.push([DIFF_EQUAL,""]);for(var g=f=d=0,b="",e="";d<a.length;){switch(a[d][0]){case DIFF_INSERT:g++;e+=a[d][1];break;case DIFF_DELETE:f++;b+=a[d][1];break;case DIFF_EQUAL:if(1<=f&&1<=g){a.splice(d-f-g,f+g);d=d-f-g;f=this.diff_main(b,e,!1,c);for(g=f.length-1;0<=g;g--)a.splice(d,0,f[g]);d+=
f.length}f=g=0;e=b=""}d++}a.pop();return a};
diff_match_patch.prototype.diff_bisect_=function(a,d,c){for(var f=a.length,g=d.length,b=Math.ceil((f+g)/2),e=2*b,h=Array(e),i=Array(e),j=0;j<e;j++)h[j]=-1,i[j]=-1;h[b+1]=0;i[b+1]=0;for(var j=f-g,k=0!=j%2,l=0,n=0,r=0,s=0,p=0;p<b&&!((new Date).getTime()>c);p++){for(var m=-p+l;m<=p-n;m+=2){var q=b+m,u;u=m==-p||m!=p&&h[q-1]<h[q+1]?h[q+1]:h[q-1]+1;for(var v=u-m;u<f&&v<g&&a.charAt(u)==d.charAt(v);)u++,v++;h[q]=u;if(u>f)n+=2;else if(v>g)l+=2;else if(k&&(q=b+j-m,0<=q&&q<e&&-1!=i[q])){var t=f-i[q];if(u>=t)return this.diff_bisectSplit_(a,
d,u,v,c)}}for(m=-p+r;m<=p-s;m+=2){q=b+m;t=m==-p||m!=p&&i[q-1]<i[q+1]?i[q+1]:i[q-1]+1;for(u=t-m;t<f&&u<g&&a.charAt(f-t-1)==d.charAt(g-u-1);)t++,u++;i[q]=t;if(t>f)s+=2;else if(u>g)r+=2;else if(!k&&(q=b+j-m,0<=q&&(q<e&&-1!=h[q])&&(u=h[q],v=b+u-q,t=f-t,u>=t)))return this.diff_bisectSplit_(a,d,u,v,c)}}return[[DIFF_DELETE,a],[DIFF_INSERT,d]]};
diff_match_patch.prototype.diff_bisectSplit_=function(a,d,c,f,g){var b=a.substring(0,c),e=d.substring(0,f),a=a.substring(c),d=d.substring(f),b=this.diff_main(b,e,!1,g),g=this.diff_main(a,d,!1,g);return b.concat(g)};
diff_match_patch.prototype.diff_linesToChars_=function(a,d){function c(b){for(var a="",e=0,c=-1,d=f.length;c<b.length-1;){c=b.indexOf("\n",e);-1==c&&(c=b.length-1);var n=b.substring(e,c+1),e=c+1;(g.hasOwnProperty?g.hasOwnProperty(n):void 0!==g[n])?a+=String.fromCharCode(g[n]):(a+=String.fromCharCode(d),g[n]=d,f[d++]=n)}return a}var f=[],g={};f[0]="";var b=c(a),e=c(d);return{chars1:b,chars2:e,lineArray:f}};
diff_match_patch.prototype.diff_charsToLines_=function(a,d){for(var c=0;c<a.length;c++){for(var f=a[c][1],g=[],b=0;b<f.length;b++)g[b]=d[f.charCodeAt(b)];a[c][1]=g.join("")}};diff_match_patch.prototype.diff_commonPrefix=function(a,d){if(!a||!d||a.charAt(0)!=d.charAt(0))return 0;for(var c=0,f=Math.min(a.length,d.length),g=f,b=0;c<g;)a.substring(b,g)==d.substring(b,g)?b=c=g:f=g,g=Math.floor((f-c)/2+c);return g};
diff_match_patch.prototype.diff_commonSuffix=function(a,d){if(!a||!d||a.charAt(a.length-1)!=d.charAt(d.length-1))return 0;for(var c=0,f=Math.min(a.length,d.length),g=f,b=0;c<g;)a.substring(a.length-g,a.length-b)==d.substring(d.length-g,d.length-b)?b=c=g:f=g,g=Math.floor((f-c)/2+c);return g};
diff_match_patch.prototype.diff_commonOverlap_=function(a,d){var c=a.length,f=d.length;if(0==c||0==f)return 0;c>f?a=a.substring(c-f):c<f&&(d=d.substring(0,c));c=Math.min(c,f);if(a==d)return c;for(var f=0,g=1;;){var b=a.substring(c-g),b=d.indexOf(b);if(-1==b)return f;g+=b;if(0==b||a.substring(c-g)==d.substring(0,g))f=g,g++}};
diff_match_patch.prototype.diff_halfMatch_=function(a,d){function c(a,e,c){for(var d=a.substring(c,c+Math.floor(a.length/4)),h=-1,f="",g,i,q,u;-1!=(h=e.indexOf(d,h+1));){var v=b.diff_commonPrefix(a.substring(c),e.substring(h)),t=b.diff_commonSuffix(a.substring(0,c),e.substring(0,h));f.length<t+v&&(f=e.substring(h-t,h)+e.substring(h,h+v),g=a.substring(0,c-t),i=a.substring(c+v),q=e.substring(0,h-t),u=e.substring(h+v))}return 2*f.length>=a.length?[g,i,q,u,f]:null}if(0>=this.Diff_Timeout)return null;
var f=a.length>d.length?a:d,g=a.length>d.length?d:a;if(4>f.length||2*g.length<f.length)return null;var b=this,e=c(f,g,Math.ceil(f.length/4)),f=c(f,g,Math.ceil(f.length/2));if(!e&&!f)return null;var e=f?e?e[4].length>f[4].length?e:f:f:e,h,i;a.length>d.length?(f=e[0],g=e[1],h=e[2],i=e[3]):(h=e[0],i=e[1],f=e[2],g=e[3]);return[f,g,h,i,e[4]]};
diff_match_patch.prototype.diff_cleanupSemantic=function(a){for(var d=!1,c=[],f=0,g=null,b=0,e=0,h=0,i=0,j=0;b<a.length;)a[b][0]==DIFF_EQUAL?(c[f++]=b,e=i,h=j,j=i=0,g=a[b][1]):(a[b][0]==DIFF_INSERT?i+=a[b][1].length:j+=a[b][1].length,g&&(g.length<=Math.max(e,h)&&g.length<=Math.max(i,j))&&(a.splice(c[f-1],0,[DIFF_DELETE,g]),a[c[f-1]+1][0]=DIFF_INSERT,f--,f--,b=0<f?c[f-1]:-1,j=i=h=e=0,g=null,d=!0)),b++;d&&this.diff_cleanupMerge(a);this.diff_cleanupSemanticLossless(a);for(b=1;b<a.length;){if(a[b-1][0]==
DIFF_DELETE&&a[b][0]==DIFF_INSERT){d=a[b-1][1];c=a[b][1];f=this.diff_commonOverlap_(d,c);g=this.diff_commonOverlap_(c,d);if(f>=g){if(f>=d.length/2||f>=c.length/2)a.splice(b,0,[DIFF_EQUAL,c.substring(0,f)]),a[b-1][1]=d.substring(0,d.length-f),a[b+1][1]=c.substring(f),b++}else if(g>=d.length/2||g>=c.length/2)a.splice(b,0,[DIFF_EQUAL,d.substring(0,g)]),a[b-1][0]=DIFF_INSERT,a[b-1][1]=c.substring(0,c.length-g),a[b+1][0]=DIFF_DELETE,a[b+1][1]=d.substring(g),b++;b++}b++}};
diff_match_patch.prototype.diff_cleanupSemanticLossless=function(a){function d(b,a){if(!b||!a)return 6;var e=b.charAt(b.length-1),c=a.charAt(0),d=e.match(diff_match_patch.nonAlphaNumericRegex_),h=c.match(diff_match_patch.nonAlphaNumericRegex_),f=d&&e.match(diff_match_patch.whitespaceRegex_),g=h&&c.match(diff_match_patch.whitespaceRegex_),e=f&&e.match(diff_match_patch.linebreakRegex_),c=g&&c.match(diff_match_patch.linebreakRegex_),i=e&&b.match(diff_match_patch.blanklineEndRegex_),j=c&&a.match(diff_match_patch.blanklineStartRegex_);
return i||j?5:e||c?4:d&&!f&&g?3:f||g?2:d||h?1:0}for(var c=1;c<a.length-1;){if(a[c-1][0]==DIFF_EQUAL&&a[c+1][0]==DIFF_EQUAL){var f=a[c-1][1],g=a[c][1],b=a[c+1][1],e=this.diff_commonSuffix(f,g);if(e)var h=g.substring(g.length-e),f=f.substring(0,f.length-e),g=h+g.substring(0,g.length-e),b=h+b;for(var e=f,h=g,i=b,j=d(f,g)+d(g,b);g.charAt(0)===b.charAt(0);){var f=f+g.charAt(0),g=g.substring(1)+b.charAt(0),b=b.substring(1),k=d(f,g)+d(g,b);k>=j&&(j=k,e=f,h=g,i=b)}a[c-1][1]!=e&&(e?a[c-1][1]=e:(a.splice(c-
1,1),c--),a[c][1]=h,i?a[c+1][1]=i:(a.splice(c+1,1),c--))}c++}};diff_match_patch.nonAlphaNumericRegex_=/[^a-zA-Z0-9]/;diff_match_patch.whitespaceRegex_=/\s/;diff_match_patch.linebreakRegex_=/[\r\n]/;diff_match_patch.blanklineEndRegex_=/\n\r?\n$/;diff_match_patch.blanklineStartRegex_=/^\r?\n\r?\n/;
diff_match_patch.prototype.diff_cleanupEfficiency=function(a){for(var d=!1,c=[],f=0,g=null,b=0,e=!1,h=!1,i=!1,j=!1;b<a.length;){if(a[b][0]==DIFF_EQUAL)a[b][1].length<this.Diff_EditCost&&(i||j)?(c[f++]=b,e=i,h=j,g=a[b][1]):(f=0,g=null),i=j=!1;else if(a[b][0]==DIFF_DELETE?j=!0:i=!0,g&&(e&&h&&i&&j||g.length<this.Diff_EditCost/2&&3==e+h+i+j))a.splice(c[f-1],0,[DIFF_DELETE,g]),a[c[f-1]+1][0]=DIFF_INSERT,f--,g=null,e&&h?(i=j=!0,f=0):(f--,b=0<f?c[f-1]:-1,i=j=!1),d=!0;b++}d&&this.diff_cleanupMerge(a)};
diff_match_patch.prototype.diff_cleanupMerge=function(a){a.push([DIFF_EQUAL,""]);for(var d=0,c=0,f=0,g="",b="",e;d<a.length;)switch(a[d][0]){case DIFF_INSERT:f++;b+=a[d][1];d++;break;case DIFF_DELETE:c++;g+=a[d][1];d++;break;case DIFF_EQUAL:1<c+f?(0!==c&&0!==f&&(e=this.diff_commonPrefix(b,g),0!==e&&(0<d-c-f&&a[d-c-f-1][0]==DIFF_EQUAL?a[d-c-f-1][1]+=b.substring(0,e):(a.splice(0,0,[DIFF_EQUAL,b.substring(0,e)]),d++),b=b.substring(e),g=g.substring(e)),e=this.diff_commonSuffix(b,g),0!==e&&(a[d][1]=b.substring(b.length-
e)+a[d][1],b=b.substring(0,b.length-e),g=g.substring(0,g.length-e))),0===c?a.splice(d-f,c+f,[DIFF_INSERT,b]):0===f?a.splice(d-c,c+f,[DIFF_DELETE,g]):a.splice(d-c-f,c+f,[DIFF_DELETE,g],[DIFF_INSERT,b]),d=d-c-f+(c?1:0)+(f?1:0)+1):0!==d&&a[d-1][0]==DIFF_EQUAL?(a[d-1][1]+=a[d][1],a.splice(d,1)):d++,c=f=0,b=g=""}""===a[a.length-1][1]&&a.pop();c=!1;for(d=1;d<a.length-1;)a[d-1][0]==DIFF_EQUAL&&a[d+1][0]==DIFF_EQUAL&&(a[d][1].substring(a[d][1].length-a[d-1][1].length)==a[d-1][1]?(a[d][1]=a[d-1][1]+a[d][1].substring(0,
a[d][1].length-a[d-1][1].length),a[d+1][1]=a[d-1][1]+a[d+1][1],a.splice(d-1,1),c=!0):a[d][1].substring(0,a[d+1][1].length)==a[d+1][1]&&(a[d-1][1]+=a[d+1][1],a[d][1]=a[d][1].substring(a[d+1][1].length)+a[d+1][1],a.splice(d+1,1),c=!0)),d++;c&&this.diff_cleanupMerge(a)};
diff_match_patch.prototype.diff_xIndex=function(a,d){var c=0,f=0,g=0,b=0,e;for(e=0;e<a.length;e++){a[e][0]!==DIFF_INSERT&&(c+=a[e][1].length);a[e][0]!==DIFF_DELETE&&(f+=a[e][1].length);if(c>d)break;g=c;b=f}return a.length!=e&&a[e][0]===DIFF_DELETE?b:b+(d-g)};
diff_match_patch.prototype.diff_prettyHtml=function(a){for(var d=[],c=/&/g,f=/</g,g=/>/g,b=/\n/g,e=0;e<a.length;e++){var h=a[e][0],i=a[e][1].replace(c,"&amp;").replace(f,"&lt;").replace(g,"&gt;").replace(b,"&para;<br>");switch(h){case DIFF_INSERT:d[e]='<ins style="background:#e6ffe6;">'+i+"</ins>";break;case DIFF_DELETE:d[e]='<del style="background:#ffe6e6;">'+i+"</del>";break;case DIFF_EQUAL:d[e]="<span>"+i+"</span>"}}return d.join("")};
diff_match_patch.prototype.diff_text1=function(a){for(var d=[],c=0;c<a.length;c++)a[c][0]!==DIFF_INSERT&&(d[c]=a[c][1]);return d.join("")};diff_match_patch.prototype.diff_text2=function(a){for(var d=[],c=0;c<a.length;c++)a[c][0]!==DIFF_DELETE&&(d[c]=a[c][1]);return d.join("")};
diff_match_patch.prototype.diff_levenshtein=function(a){for(var d=0,c=0,f=0,g=0;g<a.length;g++){var b=a[g][1];switch(a[g][0]){case DIFF_INSERT:c+=b.length;break;case DIFF_DELETE:f+=b.length;break;case DIFF_EQUAL:d+=Math.max(c,f),f=c=0}}return d+=Math.max(c,f)};
diff_match_patch.prototype.diff_toDelta=function(a){for(var d=[],c=0;c<a.length;c++)switch(a[c][0]){case DIFF_INSERT:d[c]="+"+encodeURI(a[c][1]);break;case DIFF_DELETE:d[c]="-"+a[c][1].length;break;case DIFF_EQUAL:d[c]="="+a[c][1].length}return d.join("\t").replace(/%20/g," ")};
diff_match_patch.prototype.diff_fromDelta=function(a,d){for(var c=[],f=0,g=0,b=d.split(/\t/g),e=0;e<b.length;e++){var h=b[e].substring(1);switch(b[e].charAt(0)){case "+":try{c[f++]=[DIFF_INSERT,decodeURI(h)]}catch(i){throw Error("Illegal escape in diff_fromDelta: "+h);}break;case "-":case "=":var j=parseInt(h,10);if(isNaN(j)||0>j)throw Error("Invalid number in diff_fromDelta: "+h);h=a.substring(g,g+=j);"="==b[e].charAt(0)?c[f++]=[DIFF_EQUAL,h]:c[f++]=[DIFF_DELETE,h];break;default:if(b[e])throw Error("Invalid diff operation in diff_fromDelta: "+
b[e]);}}if(g!=a.length)throw Error("Delta length ("+g+") does not equal source text length ("+a.length+").");return c};diff_match_patch.prototype.match_main=function(a,d,c){if(null==a||null==d||null==c)throw Error("Null input. (match_main)");c=Math.max(0,Math.min(c,a.length));return a==d?0:a.length?a.substring(c,c+d.length)==d?c:this.match_bitap_(a,d,c):-1};
diff_match_patch.prototype.match_bitap_=function(a,d,c){function f(a,e){var h=a/d.length,f=Math.abs(c-e);return!b.Match_Distance?f?1:h:h+f/b.Match_Distance}if(d.length>this.Match_MaxBits)throw Error("Pattern too long for this browser.");var g=this.match_alphabet_(d),b=this,e=this.Match_Threshold,h=a.indexOf(d,c);-1!=h&&(e=Math.min(f(0,h),e),h=a.lastIndexOf(d,c+d.length),-1!=h&&(e=Math.min(f(0,h),e)));for(var i=1<<d.length-1,h=-1,j,k,l=d.length+a.length,n,r=0;r<d.length;r++){j=0;for(k=l;j<k;)f(r,c+
k)<=e?j=k:l=k,k=Math.floor((l-j)/2+j);l=k;j=Math.max(1,c-k+1);var s=Math.min(c+k,a.length)+d.length;k=Array(s+2);for(k[s+1]=(1<<r)-1;s>=j;s--){var p=g[a.charAt(s-1)];k[s]=0===r?(k[s+1]<<1|1)&p:(k[s+1]<<1|1)&p|((n[s+1]|n[s])<<1|1)|n[s+1];if(k[s]&i&&(p=f(r,s-1),p<=e))if(e=p,h=s-1,h>c)j=Math.max(1,2*c-h);else break}if(f(r+1,c)>e)break;n=k}return h};
diff_match_patch.prototype.match_alphabet_=function(a){for(var d={},c=0;c<a.length;c++)d[a.charAt(c)]=0;for(c=0;c<a.length;c++)d[a.charAt(c)]|=1<<a.length-c-1;return d};
diff_match_patch.prototype.patch_addContext_=function(a,d){if(0!=d.length){for(var c=d.substring(a.start2,a.start2+a.length1),f=0;d.indexOf(c)!=d.lastIndexOf(c)&&c.length<this.Match_MaxBits-this.Patch_Margin-this.Patch_Margin;)f+=this.Patch_Margin,c=d.substring(a.start2-f,a.start2+a.length1+f);f+=this.Patch_Margin;(c=d.substring(a.start2-f,a.start2))&&a.diffs.unshift([DIFF_EQUAL,c]);(f=d.substring(a.start2+a.length1,a.start2+a.length1+f))&&a.diffs.push([DIFF_EQUAL,f]);a.start1-=c.length;a.start2-=
c.length;a.length1+=c.length+f.length;a.length2+=c.length+f.length}};
diff_match_patch.prototype.patch_make=function(a,d,c){var f;if("string"==typeof a&&"string"==typeof d&&"undefined"==typeof c)f=a,d=this.diff_main(f,d,!0),2<d.length&&(this.diff_cleanupSemantic(d),this.diff_cleanupEfficiency(d));else if(a&&"object"==typeof a&&"undefined"==typeof d&&"undefined"==typeof c)d=a,f=this.diff_text1(d);else if("string"==typeof a&&d&&"object"==typeof d&&"undefined"==typeof c)f=a;else if("string"==typeof a&&"string"==typeof d&&c&&"object"==typeof c)f=a,d=c;else throw Error("Unknown call format to patch_make.");
if(0===d.length)return[];for(var c=[],a=new diff_match_patch.patch_obj,g=0,b=0,e=0,h=f,i=0;i<d.length;i++){var j=d[i][0],k=d[i][1];!g&&j!==DIFF_EQUAL&&(a.start1=b,a.start2=e);switch(j){case DIFF_INSERT:a.diffs[g++]=d[i];a.length2+=k.length;f=f.substring(0,e)+k+f.substring(e);break;case DIFF_DELETE:a.length1+=k.length;a.diffs[g++]=d[i];f=f.substring(0,e)+f.substring(e+k.length);break;case DIFF_EQUAL:k.length<=2*this.Patch_Margin&&g&&d.length!=i+1?(a.diffs[g++]=d[i],a.length1+=k.length,a.length2+=k.length):
k.length>=2*this.Patch_Margin&&g&&(this.patch_addContext_(a,h),c.push(a),a=new diff_match_patch.patch_obj,g=0,h=f,b=e)}j!==DIFF_INSERT&&(b+=k.length);j!==DIFF_DELETE&&(e+=k.length)}g&&(this.patch_addContext_(a,h),c.push(a));return c};
diff_match_patch.prototype.patch_deepCopy=function(a){for(var d=[],c=0;c<a.length;c++){var f=a[c],g=new diff_match_patch.patch_obj;g.diffs=[];for(var b=0;b<f.diffs.length;b++)g.diffs[b]=f.diffs[b].slice();g.start1=f.start1;g.start2=f.start2;g.length1=f.length1;g.length2=f.length2;d[c]=g}return d};
diff_match_patch.prototype.patch_apply=function(a,d){if(0==a.length)return[d,[]];var a=this.patch_deepCopy(a),c=this.patch_addPadding(a),d=c+d+c;this.patch_splitMax(a);for(var f=0,g=[],b=0;b<a.length;b++){var e=a[b].start2+f,h=this.diff_text1(a[b].diffs),i,j=-1;if(h.length>this.Match_MaxBits){if(i=this.match_main(d,h.substring(0,this.Match_MaxBits),e),-1!=i&&(j=this.match_main(d,h.substring(h.length-this.Match_MaxBits),e+h.length-this.Match_MaxBits),-1==j||i>=j))i=-1}else i=this.match_main(d,h,e);
if(-1==i)g[b]=!1,f-=a[b].length2-a[b].length1;else if(g[b]=!0,f=i-e,e=-1==j?d.substring(i,i+h.length):d.substring(i,j+this.Match_MaxBits),h==e)d=d.substring(0,i)+this.diff_text2(a[b].diffs)+d.substring(i+h.length);else if(e=this.diff_main(h,e,!1),h.length>this.Match_MaxBits&&this.diff_levenshtein(e)/h.length>this.Patch_DeleteThreshold)g[b]=!1;else{this.diff_cleanupSemanticLossless(e);for(var h=0,k,j=0;j<a[b].diffs.length;j++){var l=a[b].diffs[j];l[0]!==DIFF_EQUAL&&(k=this.diff_xIndex(e,h));l[0]===
DIFF_INSERT?d=d.substring(0,i+k)+l[1]+d.substring(i+k):l[0]===DIFF_DELETE&&(d=d.substring(0,i+k)+d.substring(i+this.diff_xIndex(e,h+l[1].length)));l[0]!==DIFF_DELETE&&(h+=l[1].length)}}}d=d.substring(c.length,d.length-c.length);return[d,g]};
diff_match_patch.prototype.patch_addPadding=function(a){for(var d=this.Patch_Margin,c="",f=1;f<=d;f++)c+=String.fromCharCode(f);for(f=0;f<a.length;f++)a[f].start1+=d,a[f].start2+=d;var f=a[0],g=f.diffs;if(0==g.length||g[0][0]!=DIFF_EQUAL)g.unshift([DIFF_EQUAL,c]),f.start1-=d,f.start2-=d,f.length1+=d,f.length2+=d;else if(d>g[0][1].length){var b=d-g[0][1].length;g[0][1]=c.substring(g[0][1].length)+g[0][1];f.start1-=b;f.start2-=b;f.length1+=b;f.length2+=b}f=a[a.length-1];g=f.diffs;0==g.length||g[g.length-
1][0]!=DIFF_EQUAL?(g.push([DIFF_EQUAL,c]),f.length1+=d,f.length2+=d):d>g[g.length-1][1].length&&(b=d-g[g.length-1][1].length,g[g.length-1][1]+=c.substring(0,b),f.length1+=b,f.length2+=b);return c};
diff_match_patch.prototype.patch_splitMax=function(a){for(var d=this.Match_MaxBits,c=0;c<a.length;c++)if(!(a[c].length1<=d)){var f=a[c];a.splice(c--,1);for(var g=f.start1,b=f.start2,e="";0!==f.diffs.length;){var h=new diff_match_patch.patch_obj,i=!0;h.start1=g-e.length;h.start2=b-e.length;""!==e&&(h.length1=h.length2=e.length,h.diffs.push([DIFF_EQUAL,e]));for(;0!==f.diffs.length&&h.length1<d-this.Patch_Margin;){var e=f.diffs[0][0],j=f.diffs[0][1];e===DIFF_INSERT?(h.length2+=j.length,b+=j.length,h.diffs.push(f.diffs.shift()),
i=!1):e===DIFF_DELETE&&1==h.diffs.length&&h.diffs[0][0]==DIFF_EQUAL&&j.length>2*d?(h.length1+=j.length,g+=j.length,i=!1,h.diffs.push([e,j]),f.diffs.shift()):(j=j.substring(0,d-h.length1-this.Patch_Margin),h.length1+=j.length,g+=j.length,e===DIFF_EQUAL?(h.length2+=j.length,b+=j.length):i=!1,h.diffs.push([e,j]),j==f.diffs[0][1]?f.diffs.shift():f.diffs[0][1]=f.diffs[0][1].substring(j.length))}e=this.diff_text2(h.diffs);e=e.substring(e.length-this.Patch_Margin);j=this.diff_text1(f.diffs).substring(0,
this.Patch_Margin);""!==j&&(h.length1+=j.length,h.length2+=j.length,0!==h.diffs.length&&h.diffs[h.diffs.length-1][0]===DIFF_EQUAL?h.diffs[h.diffs.length-1][1]+=j:h.diffs.push([DIFF_EQUAL,j]));i||a.splice(++c,0,h)}}};diff_match_patch.prototype.patch_toText=function(a){for(var d=[],c=0;c<a.length;c++)d[c]=a[c];return d.join("")};
diff_match_patch.prototype.patch_fromText=function(a){var d=[];if(!a)return d;for(var a=a.split("\n"),c=0,f=/^@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@$/;c<a.length;){var g=a[c].match(f);if(!g)throw Error("Invalid patch string: "+a[c]);var b=new diff_match_patch.patch_obj;d.push(b);b.start1=parseInt(g[1],10);""===g[2]?(b.start1--,b.length1=1):"0"==g[2]?b.length1=0:(b.start1--,b.length1=parseInt(g[2],10));b.start2=parseInt(g[3],10);""===g[4]?(b.start2--,b.length2=1):"0"==g[4]?b.length2=0:(b.start2--,b.length2=
parseInt(g[4],10));for(c++;c<a.length;){g=a[c].charAt(0);try{var e=decodeURI(a[c].substring(1))}catch(h){throw Error("Illegal escape in patch_fromText: "+e);}if("-"==g)b.diffs.push([DIFF_DELETE,e]);else if("+"==g)b.diffs.push([DIFF_INSERT,e]);else if(" "==g)b.diffs.push([DIFF_EQUAL,e]);else if("@"==g)break;else if(""!==g)throw Error('Invalid patch mode "'+g+'" in: '+e);c++}}return d};diff_match_patch.patch_obj=function(){this.diffs=[];this.start2=this.start1=null;this.length2=this.length1=0};
diff_match_patch.patch_obj.prototype.toString=function(){for(var a=["@@ -"+(0===this.length1?this.start1+",0":1==this.length1?this.start1+1:this.start1+1+","+this.length1)+" +"+(0===this.length2?this.start2+",0":1==this.length2?this.start2+1:this.start2+1+","+this.length2)+" @@\n"],d,c=0;c<this.diffs.length;c++){switch(this.diffs[c][0]){case DIFF_INSERT:d="+";break;case DIFF_DELETE:d="-";break;case DIFF_EQUAL:d=" "}a[c+1]=d+encodeURI(this.diffs[c][1])+"\n"}return a.join("").replace(/%20/g," ")};
this.diff_match_patch=diff_match_patch;this.DIFF_DELETE=DIFF_DELETE;this.DIFF_INSERT=DIFF_INSERT;this.DIFF_EQUAL=DIFF_EQUAL;var JSON;JSON||(JSON={});
(function(){function a(c,h){var f,g,r,s,p=b,m,q=h[c];q&&"object"==typeof q&&"function"==typeof q.toJSON&&(q=q.toJSON(c));"function"==typeof i&&(q=i.call(h,c,q));switch(typeof q){case "string":return d(q);case "number":return isFinite(q)?String(q):"null";case "boolean":case "null":return String(q);case "object":if(!q)return"null";b+=e;m=[];if("[object Array]"===Object.prototype.toString.apply(q)){s=q.length;for(f=0;f<s;f+=1)m[f]=a(f,q)||"null";r=0===m.length?"[]":b?"[\n"+b+m.join(",\n"+b)+"\n"+p+"]":
"["+m.join(",")+"]";b=p;return r}if(i&&"object"==typeof i){s=i.length;for(f=0;f<s;f+=1)"string"==typeof i[f]&&(g=i[f],r=a(g,q),r&&m.push(d(g)+(b?": ":":")+r))}else for(g in q)Object.prototype.hasOwnProperty.call(q,g)&&(r=a(g,q),r&&m.push(d(g)+(b?": ":":")+r));r=0===m.length?"{}":b?"{\n"+b+m.join(",\n"+b)+"\n"+p+"}":"{"+m.join(",")+"}";b=p;return r}}function d(b){g.lastIndex=0;return g.test(b)?'"'+b.replace(g,function(b){var a=h[b];return"string"==typeof a?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+b+'"'}function c(b){return 10>b?"0"+b:b}"use strict";"function"!=typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b,e,h={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;"function"!=typeof JSON.stringify&&(JSON.stringify=function(c,d,h){var f;e=b="";if("number"==typeof h)for(f=0;f<h;f+=1)e+=" ";else"string"==typeof h&&(e=h);i=d;if(!d||"function"==typeof d||"object"==typeof d&&"number"==typeof d.length)return a("",{"":c});throw Error("JSON.stringify");});"function"!=
typeof JSON.parse&&(JSON.parse=function(b,a){function e(b,c){var d,h,f=b[c];if(f&&"object"==typeof f)for(d in f)Object.prototype.hasOwnProperty.call(f,d)&&(h=e(f,d),void 0!==h?f[d]=h:delete f[d]);return a.call(b,c,f)}var c,b=String(b);f.lastIndex=0;f.test(b)&&(b=b.replace(f,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return c=eval("("+b+")"),"function"==typeof a?e({"":c},""):c;throw new SyntaxError("JSON.parse");})})();
SockJS=function(){var a=document,d=window,c={},f=function(){};f.prototype.addEventListener=function(b,a){this._listeners||(this._listeners={});b in this._listeners||(this._listeners[b]=[]);var e=this._listeners[b];-1===c.arrIndexOf(e,a)&&e.push(a)};f.prototype.removeEventListener=function(b,a){if(this._listeners&&b in this._listeners){var e=this._listeners[b],d=c.arrIndexOf(e,a);-1!==d&&(1<e.length?this._listeners[b]=e.slice(0,d).concat(e.slice(d+1)):delete this._listeners[b])}};f.prototype.dispatchEvent=
function(b){var a=b.type,e=Array.prototype.slice.call(arguments,0);this["on"+a]&&this["on"+a].apply(this,e);if(this._listeners&&a in this._listeners)for(var c=0;c<this._listeners[a].length;c++)this._listeners[a][c].apply(this,e)};var g=function(b,a){this.type=b;if("undefined"!==typeof a)for(var e in a)a.hasOwnProperty(e)&&(this[e]=a[e])};g.prototype.toString=function(){var b=[],a;for(a in this)if(this.hasOwnProperty(a)){var e=this[a];"function"===typeof e&&(e="[function]");b.push(a+"="+e)}return"SimpleEvent("+
b.join(", ")+")"};var b=function(b){this._events=b||[];this._listeners={}};b.prototype.emit=function(b){this._verifyType(b);if(!this._nuked){var a=Array.prototype.slice.call(arguments,1);this["on"+b]&&this["on"+b].apply(this,a);if(b in this._listeners)for(var e=0;e<this._listeners[b].length;e++)this._listeners[b][e].apply(this,a)}};b.prototype.on=function(b,a){this._verifyType(b);this._nuked||(b in this._listeners||(this._listeners[b]=[]),this._listeners[b].push(a))};b.prototype._verifyType=function(b){-1===
c.arrIndexOf(this._events,b)&&c.log("Event "+JSON.stringify(b)+" not listed "+JSON.stringify(this._events)+" in "+this)};b.prototype.nuke=function(){this._nuked=!0;for(var b=0;b<this._events.length;b++)delete this[this._events[b]];this._listeners={}};c.random_string=function(b,a){var a=a||37,e,c=[];for(e=0;e<b;e++)c.push("abcdefghijklmnopqrstuvwxyz0123456789_".substr(Math.floor(Math.random()*a),1));return c.join("")};c.random_number=function(b){return Math.floor(Math.random()*b)};c.random_number_string=
function(b){var a=(""+(b-1)).length;return(Array(a+1).join("0")+c.random_number(b)).slice(-a)};c.getOrigin=function(b){return(b+"/").split("/").slice(0,3).join("/")};c.isSameOriginUrl=function(b,a){a||(a=d.location.href);return b.split("/").slice(0,3).join("/")===a.split("/").slice(0,3).join("/")};c.getParentDomain=function(b){return/^[0-9.]*$/.test(b)||/^\[/.test(b)||!/[.]/.test(b)?b:b.split(".").slice(1).join(".")};c.objectExtend=function(b,a){for(var e in a)a.hasOwnProperty(e)&&(b[e]=a[e]);return b};
c.polluteGlobalNamespace=function(){"_jp"in d||(d._jp={})};c.closeFrame=function(b,a){return"c"+JSON.stringify([b,a])};c.userSetCode=function(b){return 1E3===b||3E3<=b&&4999>=b};c.countRTO=function(b){return 100<b?3*b:b+200};c.log=function(){d.console&&(console.log&&console.log.apply)&&console.log.apply(console,arguments)};c.bind=function(b,a){return b.bind?b.bind(a):function(){return b.apply(a,arguments)}};c.flatUrl=function(b){return-1===b.indexOf("?")&&-1===b.indexOf("#")};c.amendUrl=function(b){var e=
a.location;if(!b)throw Error("Wrong url for SockJS");if(!c.flatUrl(b))throw Error("Only basic urls are supported in SockJS");0===b.indexOf("//")&&(b=e.protocol+b);0===b.indexOf("/")&&(b=e.protocol+"//"+e.host+b);return b=b.replace(/[/]+$/,"")};c.arrIndexOf=function(b,a){for(var e=0;e<b.length;e++)if(b[e]===a)return e;return-1};c.arrSkip=function(b,a){var e=c.arrIndexOf(b,a);return-1===e?b.slice():b.slice(0,e).concat(b.slice(e+1))};c.isArray=Array.isArray||function(b){return 0<={}.toString.call(b).indexOf("Array")};
c.delay=function(b,a){"function"===typeof b&&(a=b,b=0);return setTimeout(a,b)};var e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h={"\x00":"\\u0000","\u0001":"\\u0001","\u0002":"\\u0002","\u0003":"\\u0003","\u0004":"\\u0004","\u0005":"\\u0005","\u0006":"\\u0006","\u0007":"\\u0007","\b":"\\b","\t":"\\t","\n":"\\n","\x0B":"\\u000b","\f":"\\f","\r":"\\r","\u000e":"\\u000e","\u000f":"\\u000f","\u0010":"\\u0010","\u0011":"\\u0011",
"\u0012":"\\u0012","\u0013":"\\u0013","\u0014":"\\u0014","\u0015":"\\u0015","\u0016":"\\u0016","\u0017":"\\u0017","\u0018":"\\u0018","\u0019":"\\u0019","\u001a":"\\u001a","\u001b":"\\u001b","\u001c":"\\u001c","\u001d":"\\u001d","\u001e":"\\u001e","\u001f":"\\u001f",'"':'\\"',"\\":"\\\\","\u007f":"\\u007f","\u0080":"\\u0080","\u0081":"\\u0081","\u0082":"\\u0082","\u0083":"\\u0083","\u0084":"\\u0084","\u0085":"\\u0085","\u0086":"\\u0086","\u0087":"\\u0087","\u0088":"\\u0088","\u0089":"\\u0089","\u008a":"\\u008a",
"\u008b":"\\u008b","\u008c":"\\u008c","\u008d":"\\u008d","\u008e":"\\u008e","\u008f":"\\u008f","\u0090":"\\u0090","\u0091":"\\u0091","\u0092":"\\u0092","\u0093":"\\u0093","\u0094":"\\u0094","\u0095":"\\u0095","\u0096":"\\u0096","\u0097":"\\u0097","\u0098":"\\u0098","\u0099":"\\u0099","\u009a":"\\u009a","\u009b":"\\u009b","\u009c":"\\u009c","\u009d":"\\u009d","\u009e":"\\u009e","\u009f":"\\u009f","\u00ad":"\\u00ad","\u0600":"\\u0600","\u0601":"\\u0601","\u0602":"\\u0602","\u0603":"\\u0603","\u0604":"\\u0604",
"\u070f":"\\u070f","\u17b4":"\\u17b4","\u17b5":"\\u17b5","\u200c":"\\u200c","\u200d":"\\u200d","\u200e":"\\u200e","\u200f":"\\u200f","\u2028":"\\u2028","\u2029":"\\u2029","\u202a":"\\u202a","\u202b":"\\u202b","\u202c":"\\u202c","\u202d":"\\u202d","\u202e":"\\u202e","\u202f":"\\u202f","\u2060":"\\u2060","\u2061":"\\u2061","\u2062":"\\u2062","\u2063":"\\u2063","\u2064":"\\u2064","\u2065":"\\u2065","\u2066":"\\u2066","\u2067":"\\u2067","\u2068":"\\u2068","\u2069":"\\u2069","\u206a":"\\u206a","\u206b":"\\u206b",
"\u206c":"\\u206c","\u206d":"\\u206d","\u206e":"\\u206e","\u206f":"\\u206f","\ufeff":"\\ufeff","\ufff0":"\\ufff0","\ufff1":"\\ufff1","\ufff2":"\\ufff2","\ufff3":"\\ufff3","\ufff4":"\\ufff4","\ufff5":"\\ufff5","\ufff6":"\\ufff6","\ufff7":"\\ufff7","\ufff8":"\\ufff8","\ufff9":"\\ufff9","\ufffa":"\\ufffa","\ufffb":"\\ufffb","\ufffc":"\\ufffc","\ufffd":"\\ufffd","\ufffe":"\\ufffe","\uffff":"\\uffff"},i=/[\x00-\x1f\ud800-\udfff\ufffe\uffff\u0300-\u0333\u033d-\u0346\u034a-\u034c\u0350-\u0352\u0357-\u0358\u035c-\u0362\u0374\u037e\u0387\u0591-\u05af\u05c4\u0610-\u0617\u0653-\u0654\u0657-\u065b\u065d-\u065e\u06df-\u06e2\u06eb-\u06ec\u0730\u0732-\u0733\u0735-\u0736\u073a\u073d\u073f-\u0741\u0743\u0745\u0747\u07eb-\u07f1\u0951\u0958-\u095f\u09dc-\u09dd\u09df\u0a33\u0a36\u0a59-\u0a5b\u0a5e\u0b5c-\u0b5d\u0e38-\u0e39\u0f43\u0f4d\u0f52\u0f57\u0f5c\u0f69\u0f72-\u0f76\u0f78\u0f80-\u0f83\u0f93\u0f9d\u0fa2\u0fa7\u0fac\u0fb9\u1939-\u193a\u1a17\u1b6b\u1cda-\u1cdb\u1dc0-\u1dcf\u1dfc\u1dfe\u1f71\u1f73\u1f75\u1f77\u1f79\u1f7b\u1f7d\u1fbb\u1fbe\u1fc9\u1fcb\u1fd3\u1fdb\u1fe3\u1feb\u1fee-\u1fef\u1ff9\u1ffb\u1ffd\u2000-\u2001\u20d0-\u20d1\u20d4-\u20d7\u20e7-\u20e9\u2126\u212a-\u212b\u2329-\u232a\u2adc\u302b-\u302c\uaab2-\uaab3\uf900-\ufa0d\ufa10\ufa12\ufa15-\ufa1e\ufa20\ufa22\ufa25-\ufa26\ufa2a-\ufa2d\ufa30-\ufa6d\ufa70-\ufad9\ufb1d\ufb1f\ufb2a-\ufb36\ufb38-\ufb3c\ufb3e\ufb40-\ufb41\ufb43-\ufb44\ufb46-\ufb4e\ufff0-\uffff]/g,
j,k=JSON&&JSON.stringify||function(b){e.lastIndex=0;e.test(b)&&(b=b.replace(e,function(b){return h[b]}));return'"'+b+'"'};c.quote=function(b){b=k(b);i.lastIndex=0;if(!i.test(b))return b;if(!j){var a,e={},c=[];for(a=0;65536>a;a++)c.push(String.fromCharCode(a));i.lastIndex=0;c.join("").replace(i,function(b){e[b]="\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4);return""});i.lastIndex=0;j=e}return b.replace(i,function(b){return j[b]})};var l="websocket xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile xdr-polling xhr-polling iframe-xhr-polling jsonp-polling".split(" ");
c.probeProtocols=function(){for(var b={},a=0;a<l.length;a++){var e=l[a];b[e]=m[e]&&m[e].enabled()}return b};c.detectProtocols=function(b,a,e){var c={},d=[];a||(a=l);for(var h=0;h<a.length;h++){var f=a[h];c[f]=b[f]}var g=function(b){var a=b.shift();c[a]?d.push(a):0<b.length&&g(b)};!1!==e.websocket&&g(["websocket"]);c["xhr-streaming"]&&!e.null_origin?d.push("xhr-streaming"):c["xdr-streaming"]&&!e.cookie_needed&&!e.null_origin?d.push("xdr-streaming"):g(["iframe-eventsource","iframe-htmlfile"]);c["xhr-polling"]&&
!e.null_origin?d.push("xhr-polling"):c["xdr-polling"]&&!e.cookie_needed&&!e.null_origin?d.push("xdr-polling"):g(["iframe-xhr-polling","jsonp-polling"]);return d};c.createHook=function(){var b="a"+c.random_string(8);if(!("_sockjs_global"in d)){var a={};d._sockjs_global=function(b){b in a||(a[b]={id:b,del:function(){delete a[b]}});return a[b]}}return d._sockjs_global(b)};c.attachMessage=function(b){c.attachEvent("message",b)};c.attachEvent=function(b,e){"undefined"!==typeof d.addEventListener?d.addEventListener(b,
e,!1):(a.attachEvent("on"+b,e),d.attachEvent("on"+b,e))};c.detachMessage=function(b){c.detachEvent("message",b)};c.detachEvent=function(b,e){"undefined"!==typeof d.addEventListener?d.removeEventListener(b,e,!1):(a.detachEvent("on"+b,e),d.detachEvent("on"+b,e))};var n={},r=!1,s=function(){for(var b in n)n[b](),delete n[b]};c.attachEvent("unload",function(){r||(r=!0,s())});c.unload_add=function(b){var a=c.random_string(8);n[a]=b;r&&c.delay(s);return a};c.unload_del=function(b){b in n&&delete n[b]};
c.createIframe=function(b,e){var d=a.createElement("iframe"),h,f,g=function(){clearTimeout(h);try{d.onload=null}catch(b){}d.onerror=null},i=function(){d&&(g(),setTimeout(function(){d&&d.parentNode.removeChild(d);d=null},0),c.unload_del(f))},j=function(b){d&&(i(),e(b))};d.src=b;d.style.display="none";d.style.position="absolute";d.onerror=function(){j("onerror")};d.onload=function(){clearTimeout(h);h=setTimeout(function(){j("onload timeout")},2E3)};a.body.appendChild(d);h=setTimeout(function(){j("timeout")},
15E3);f=c.unload_add(i);return{post:function(b,a){try{d&&d.contentWindow&&d.contentWindow.postMessage(b,a)}catch(e){}},cleanup:i,loaded:g}};c.createHtmlfile=function(b,a){var e=new ActiveXObject("htmlfile"),h,f,g,i=function(){clearTimeout(h)},j=function(){e&&(i(),c.unload_del(f),g.parentNode.removeChild(g),g=e=null,CollectGarbage())};e.open();e.write('<html><script>document.domain="'+document.domain+'";<\/script></html>');e.close();e.parentWindow._jp=d._jp;var k=e.createElement("div");e.body.appendChild(k);
g=e.createElement("iframe");k.appendChild(g);g.src=b;h=setTimeout(function(){e&&(j(),a("timeout"))},15E3);f=c.unload_add(j);return{post:function(b,a){try{g&&g.contentWindow&&g.contentWindow.postMessage(b,a)}catch(e){}},cleanup:j,loaded:i}};var p=function(){};p.prototype=new b(["chunk","finish"]);p.prototype._start=function(b,a,e,h){var f=this;try{f.xhr=new XMLHttpRequest}catch(g){}if(!f.xhr)try{f.xhr=new d.ActiveXObject("Microsoft.XMLHTTP")}catch(i){}if(d.ActiveXObject||d.XDomainRequest)a+=(-1===
a.indexOf("?")?"?":"&")+"t="+ +new Date;f.unload_ref=c.unload_add(function(){f._cleanup(!0)});try{f.xhr.open(b,a,!0)}catch(j){f.emit("finish",0,"");f._cleanup();return}if(!h||!h.no_credentials)f.xhr.withCredentials="true";if(h&&h.headers)for(var k in h.headers)f.xhr.setRequestHeader(k,h.headers[k]);f.xhr.onreadystatechange=function(){if(f.xhr){var b=f.xhr;switch(b.readyState){case 3:try{var a=b.status,e=b.responseText}catch(c){}1223===a&&(a=204);e&&0<e.length&&f.emit("chunk",a,e);break;case 4:a=b.status,
1223===a&&(a=204),f.emit("finish",a,b.responseText),f._cleanup(!1)}}};f.xhr.send(e)};p.prototype._cleanup=function(b){if(this.xhr){c.unload_del(this.unload_ref);this.xhr.onreadystatechange=function(){};if(b)try{this.xhr.abort()}catch(a){}this.unload_ref=this.xhr=null}};p.prototype.close=function(){this.nuke();this._cleanup(!0)};(c.XHRCorsObject=function(){var b=this,a=arguments;c.delay(function(){b._start.apply(b,a)})}).prototype=new p;(c.XHRLocalObject=function(b,a,e){var d=this;c.delay(function(){d._start(b,
a,e,{no_credentials:!0})})}).prototype=new p;p=c.XDRObject=function(b,a,e){var d=this;c.delay(function(){d._start(b,a,e)})};p.prototype=new b(["chunk","finish"]);p.prototype._start=function(b,a,e){var d=this,h=new XDomainRequest,a=a+((-1===a.indexOf("?")?"?":"&")+"t="+ +new Date),f=h.ontimeout=h.onerror=function(){d.emit("finish",0,"");d._cleanup(!1)};h.onprogress=function(){d.emit("chunk",200,h.responseText)};h.onload=function(){d.emit("finish",200,h.responseText);d._cleanup(!1)};d.xdr=h;d.unload_ref=
c.unload_add(function(){d._cleanup(!0)});try{d.xdr.open(b,a),d.xdr.send(e)}catch(g){f()}};p.prototype._cleanup=function(b){if(this.xdr){c.unload_del(this.unload_ref);this.xdr.ontimeout=this.xdr.onerror=this.xdr.onprogress=this.xdr.onload=null;if(b)try{this.xdr.abort()}catch(a){}this.unload_ref=this.xdr=null}};p.prototype.close=function(){this.nuke();this._cleanup(!0)};c.isXHRCorsCapable=function(){return d.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest?1:d.XDomainRequest&&a.domain?2:w.enabled()?
3:4};var m=function(b,a,e){if(this===d)return new m(b,a,e);var h=this,f;h._options={devel:!1,debug:!1,protocols_whitelist:[],info:void 0,rtt:void 0};e&&c.objectExtend(h._options,e);h._base_url=c.amendUrl(b);h._server=h._options.server||c.random_number_string(1E3);h._options.protocols_whitelist&&h._options.protocols_whitelist.length?f=h._options.protocols_whitelist:(f="string"===typeof a&&0<a.length?[a]:c.isArray(a)?a:null)&&h._debug('Deprecated API: Use "protocols_whitelist" option instead of supplying protocol list as a second parameter to SockJS constructor.');
h._protocols=[];h.protocol=null;h.readyState=m.CONNECTING;h._ir=J(h._base_url);h._ir.onfinish=function(b,a){h._ir=null;b?(h._options.info&&(b=c.objectExtend(b,h._options.info)),h._options.rtt&&(a=h._options.rtt),h._applyInfo(b,a,f),h._didClose()):h._didClose(1002,"Can't connect to server",!0)}};m.prototype=new f;m.version="0.3.4";m.CONNECTING=0;m.OPEN=1;m.CLOSING=2;m.CLOSED=3;m.prototype._debug=function(){this._options.debug&&c.log.apply(c,arguments)};m.prototype._dispatchOpen=function(){this.readyState===
m.CONNECTING?(this._transport_tref&&(clearTimeout(this._transport_tref),this._transport_tref=null),this.readyState=m.OPEN,this.dispatchEvent(new g("open"))):this._didClose(1006,"Server lost session")};m.prototype._dispatchMessage=function(b){this.readyState===m.OPEN&&this.dispatchEvent(new g("message",{data:b}))};m.prototype._dispatchHeartbeat=function(){this.readyState===m.OPEN&&this.dispatchEvent(new g("heartbeat",{}))};m.prototype._didClose=function(b,a,e){var d=this;if(d.readyState!==m.CONNECTING&&
d.readyState!==m.OPEN&&d.readyState!==m.CLOSING)throw Error("INVALID_STATE_ERR");d._ir&&(d._ir.nuke(),d._ir=null);d._transport&&(d._transport.doCleanup(),d._transport=null);var h=new g("close",{code:b,reason:a,wasClean:c.userSetCode(b)});if(!c.userSetCode(b)&&d.readyState===m.CONNECTING&&!e){if(d._try_next_protocol(h))return;h=new g("close",{code:2E3,reason:"All transports failed",wasClean:!1,last_event:h})}d.readyState=m.CLOSED;c.delay(function(){d.dispatchEvent(h)})};m.prototype._didMessage=function(b){switch(b.slice(0,
1)){case "o":this._dispatchOpen();break;case "a":for(var b=JSON.parse(b.slice(1)||"[]"),a=0;a<b.length;a++)this._dispatchMessage(b[a]);break;case "m":b=JSON.parse(b.slice(1)||"null");this._dispatchMessage(b);break;case "c":b=JSON.parse(b.slice(1)||"[]");this._didClose(b[0],b[1]);break;case "h":this._dispatchHeartbeat()}};m.prototype._try_next_protocol=function(b){var e=this;e.protocol&&(e._debug("Closed transport:",e.protocol,""+b),e.protocol=null);e._transport_tref&&(clearTimeout(e._transport_tref),
e._transport_tref=null);for(;;){b=e.protocol=e._protocols.shift();if(!b)return!1;if(m[b]&&!0===m[b].need_body&&(!a.body||"undefined"!==typeof a.readyState&&"complete"!==a.readyState))return e._protocols.unshift(b),e.protocol="waiting-for-load",c.attachEvent("load",function(){e._try_next_protocol()}),!0;if(!m[b]||!m[b].enabled(e._options))e._debug("Skipping transport:",b);else{e._transport_tref=c.delay((e._options.rto||0)*(m[b].roundTrips||1)||5E3,function(){e.readyState===m.CONNECTING&&e._didClose(2007,
"Transport timeouted")});var d=c.random_string(8),d=e._base_url+"/"+e._server+"/"+d;e._debug("Opening transport:",b," url:"+d," RTO:"+e._options.rto);e._transport=new m[b](e,d,e._base_url);return!0}}};m.prototype.close=function(b,a){if(b&&!c.userSetCode(b))throw Error("INVALID_ACCESS_ERR");if(this.readyState!==m.CONNECTING&&this.readyState!==m.OPEN)return!1;this.readyState=m.CLOSING;this._didClose(b||1E3,a||"Normal closure");return!0};m.prototype.send=function(b){if(this.readyState===m.CONNECTING)throw Error("INVALID_STATE_ERR");
this.readyState===m.OPEN&&this._transport.doSend(c.quote(""+b));return!0};m.prototype._applyInfo=function(b,e,d){this._options.info=b;this._options.rtt=e;this._options.rto=c.countRTO(e);this._options.info.null_origin=!a.domain;e=c.probeProtocols();this._protocols=c.detectProtocols(e,d,b)};p=m.websocket=function(b,a){var e=this,h=a+"/websocket",h="https"===h.slice(0,5)?"wss"+h.slice(5):"ws"+h.slice(4);e.ri=b;e.url=h;e.ws=new (d.WebSocket||d.MozWebSocket)(e.url);e.ws.onmessage=function(b){e.ri._didMessage(b.data)};
e.unload_ref=c.unload_add(function(){e.ws.close()});e.ws.onclose=function(){e.ri._didMessage(c.closeFrame(1006,"WebSocket connection broken"))}};p.prototype.doSend=function(b){this.ws.send("["+b+"]")};p.prototype.doCleanup=function(){var b=this.ws;b&&(b.onmessage=b.onclose=null,b.close(),c.unload_del(this.unload_ref),this.unload_ref=this.ri=this.ws=null)};p.enabled=function(){return!(!d.WebSocket&&!d.MozWebSocket)};p.roundTrips=2;var q=function(){};q.prototype.send_constructor=function(b){this.send_buffer=
[];this.sender=b};q.prototype.doSend=function(b){this.send_buffer.push(b);this.send_stop||this.send_schedule()};q.prototype.send_schedule_wait=function(){var b=this,a;b.send_stop=function(){b.send_stop=null;clearTimeout(a)};a=c.delay(25,function(){b.send_stop=null;b.send_schedule()})};q.prototype.send_schedule=function(){var b=this;if(0<b.send_buffer.length){var a="["+b.send_buffer.join(",")+"]";b.send_stop=b.sender(b.trans_url,a,function(a,e){b.send_stop=null;!1===a?b.ri._didClose(1006,"Sending error "+
e):b.send_schedule_wait()});b.send_buffer=[]}};q.prototype.send_destructor=function(){this._send_stop&&this._send_stop();this._send_stop=null};var u=function(b,e,d){if(!("_send_form"in this)){var h=this._send_form=a.createElement("form"),f=this._send_area=a.createElement("textarea");f.name="d";h.style.display="none";h.style.position="absolute";h.method="POST";h.enctype="application/x-www-form-urlencoded";h.acceptCharset="UTF-8";h.appendChild(f);a.body.appendChild(h)}var h=this._send_form,f=this._send_area,
g="a"+c.random_string(8);h.target=g;h.action=b+"/jsonp_send?i="+g;var i;try{i=a.createElement('<iframe name="'+g+'">')}catch(j){i=a.createElement("iframe"),i.name=g}i.id=g;h.appendChild(i);i.style.display="none";try{f.value=e}catch(k){c.log("Your browser is seriously broken. Go home! "+k.message)}h.submit();var l=function(){i.onerror&&(i.onreadystatechange=i.onerror=i.onload=null,c.delay(500,function(){i.parentNode.removeChild(i);i=null}),f.value="",d(!0))};i.onerror=i.onload=l;i.onreadystatechange=
function(){"complete"==i.readyState&&l()};return l},v=function(b){return function(a,e,c){(new b("POST",a+"/xhr_send",e)).onfinish=function(b){c(200===b||204===b,"http status "+b)};return function(b){c(!1,b)}}},p=m["jsonp-polling"]=function(b,a){c.polluteGlobalNamespace();this.ri=b;this.trans_url=a;this.send_constructor(u);this._schedule_recv()};p.prototype=new q;p.prototype._schedule_recv=function(){var b=this,e=b.trans_url+"/jsonp",h=function(a){b._recv_stop=null;a&&(b._is_closing||b.ri._didMessage(a));
b._is_closing||b._schedule_recv()},f="a"+c.random_string(6),g=0,e=e+"?c="+escape("_jp."+f),i=function(b){switch(g){case 0:delete d._jp[f];h(b);break;case 1:h(b);g=2;break;case 2:delete d._jp[f]}},j,k=a.createElement("script"),l,m=function(b){l&&(l.parentNode.removeChild(l),l=null);k&&(clearTimeout(j),k.parentNode.removeChild(k),k=k.onreadystatechange=k.onerror=k.onload=k.onclick=null,i(b),i=null)},n=!1,p=null;k.id="a"+c.random_string(8);k.src=e;k.type="text/javascript";k.charset="UTF-8";k.onerror=
function(){p||(p=setTimeout(function(){n||m(c.closeFrame(1006,"JSONP script loaded abnormally (onerror)"))},1E3))};k.onload=function(){m(c.closeFrame(1006,"JSONP script loaded abnormally (onload)"))};k.onreadystatechange=function(){if(/loaded|closed/.test(k.readyState)){if(k&&k.htmlFor&&k.onclick){n=!0;try{k.onclick()}catch(b){}}k&&m(c.closeFrame(1006,"JSONP script loaded abnormally (onreadystatechange)"))}};if("undefined"===typeof k.async&&a.attachEvent)if(/opera/i.test(navigator.userAgent))l=a.createElement("script"),
l.text="try{var a = document.getElementById('"+k.id+"'); if(a)a.onerror();}catch(x){};",k.async=l.async=!1;else{try{k.htmlFor=k.id,k.event="onclick"}catch(q){}k.async=!0}"undefined"!==typeof k.async&&(k.async=!0);j=setTimeout(function(){m(c.closeFrame(1006,"JSONP script loaded abnormally (timeout)"))},35E3);e=a.getElementsByTagName("head")[0];e.insertBefore(k,e.firstChild);l&&e.insertBefore(l,e.firstChild);d._jp[f]=m;b._recv_stop=function(){d._jp[f]&&(g=1,d._jp[f](c.closeFrame(1E3,"JSONP user aborted read")))}};
p.enabled=function(){return!0};p.need_body=!0;p.prototype.doCleanup=function(){this._is_closing=!0;this._recv_stop&&this._recv_stop();this.ri=this._recv_stop=null;this.send_destructor()};p=function(){};p.prototype=new q;p.prototype.run=function(b,a,e,c,d){this.ri=b;this.trans_url=a;this.send_constructor(v(d));this.poll=new C(b,c,a+e,d)};p.prototype.doCleanup=function(){this.poll&&(this.poll.abort(),this.poll=null)};var t=m["xhr-streaming"]=function(b,a){this.run(b,a,"/xhr_streaming",y,c.XHRCorsObject)};
t.prototype=new p;t.enabled=function(){return d.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&!/opera/i.test(navigator.userAgent)};t.roundTrips=2;t.need_body=!0;q=m["xdr-streaming"]=function(b,a){this.run(b,a,"/xhr_streaming",y,c.XDRObject)};q.prototype=new p;q.enabled=function(){return!!d.XDomainRequest};q.roundTrips=2;var z=m["xhr-polling"]=function(b,a){this.run(b,a,"/xhr",y,c.XHRCorsObject)};z.prototype=new p;z.enabled=t.enabled;z.roundTrips=2;t=m["xdr-polling"]=function(b,a){this.run(b,
a,"/xhr",y,c.XDRObject)};t.prototype=new p;t.enabled=q.enabled;t.roundTrips=2;var w=function(){};w.prototype.i_constructor=function(b,a,e){var d=this;d.ri=b;d.origin=c.getOrigin(e);d.base_url=e;d.trans_url=a;b=e+"/iframe.html";d.ri._options.devel&&(b+="?t="+ +new Date);d.window_id=c.random_string(8);b+="#"+d.window_id;d.iframeObj=c.createIframe(b,function(b){d.ri._didClose(1006,"Unable to load an iframe ("+b+")")});d.onmessage_cb=c.bind(d.onmessage,d);c.attachMessage(d.onmessage_cb)};w.prototype.doCleanup=
function(){if(this.iframeObj){c.detachMessage(this.onmessage_cb);try{this.iframeObj.iframe.contentWindow&&this.postMessage("c")}catch(b){}this.iframeObj.cleanup();this.onmessage_cb=this.iframeObj=this.iframeObj=null}};w.prototype.onmessage=function(b){if(b.origin===this.origin){var a=b.data.slice(0,8),e=b.data.slice(8,9),b=b.data.slice(9);if(a===this.window_id)switch(e){case "s":this.iframeObj.loaded();this.postMessage("s",JSON.stringify([m.version,this.protocol,this.trans_url,this.base_url]));break;
case "t":this.ri._didMessage(b)}}};w.prototype.postMessage=function(b,a){this.iframeObj.post(this.window_id+b+(a||""),this.origin)};w.prototype.doSend=function(b){this.postMessage("m",b)};w.enabled=function(){var b=navigator&&navigator.userAgent&&-1!==navigator.userAgent.indexOf("Konqueror");return("function"===typeof d.postMessage||"object"===typeof d.postMessage)&&!b};var D,E=function(b,a){parent!==d?parent.postMessage(D+b+(a||""),"*"):c.log("Can't postMessage, no parent window.",b,a)},x=function(){};
x.prototype._didClose=function(b,a){E("t",c.closeFrame(b,a))};x.prototype._didMessage=function(b){E("t",b)};x.prototype._doSend=function(b){this._transport.doSend(b)};x.prototype._doCleanup=function(){this._transport.doCleanup()};c.parent_origin=void 0;m.bootstrap_iframe=function(){var b;D=a.location.hash.slice(1);c.attachMessage(function(a){if(a.source===parent&&("undefined"===typeof c.parent_origin&&(c.parent_origin=a.origin),a.origin===c.parent_origin)){var e=a.data.slice(0,8),h=a.data.slice(8,
9),a=a.data.slice(9);if(e===D)switch(h){case "s":var f=JSON.parse(a),e=f[0],h=f[1],a=f[2],f=f[3];e!==m.version&&c.log('Incompatibile SockJS! Main site uses: "'+e+'", the iframe: "'+m.version+'".');if(!c.flatUrl(a)||!c.flatUrl(f)){c.log("Only basic urls are supported in SockJS");break}if(!c.isSameOriginUrl(a)||!c.isSameOriginUrl(f)){c.log("Can't connect to different domain from within an iframe. ("+JSON.stringify([d.location.href,a,f])+")");break}b=new x;b._transport=new x[h](b,a,f);break;case "m":b._doSend(a);
break;case "c":b&&b._doCleanup(),b=null}}});E("s")};var A=function(b,a){var e=this;c.delay(function(){e.doXhr(b,a)})};A.prototype=new b(["finish"]);A.prototype.doXhr=function(b,a){var e=this,d=(new Date).getTime(),h=new a("GET",b+"/info"),f=c.delay(8E3,function(){h.ontimeout()});h.onfinish=function(b,a){clearTimeout(f);f=null;if(200===b){var c=(new Date).getTime()-d,h=JSON.parse(a);"object"!==typeof h&&(h={});e.emit("finish",h,c)}else e.emit("finish")};h.ontimeout=function(){h.close();e.emit("finish")}};
var H=function(b){var e=this,d=function(){var a=new w;a.protocol="w-iframe-info-receiver";var c=function(b){"string"===typeof b&&"m"===b.substr(0,1)?(b=JSON.parse(b.substr(1)),e.emit("finish",b[0],b[1])):e.emit("finish");a.doCleanup();a=null};a.i_constructor({_options:{},_didClose:c,_didMessage:c},b,b)};a.body?d():c.attachEvent("load",d)};H.prototype=new b(["finish"]);var I=function(){var b=this;c.delay(function(){b.emit("finish",{},2E3)})};I.prototype=new b(["finish"]);var J=function(b){if(c.isSameOriginUrl(b))return new A(b,
c.XHRLocalObject);switch(c.isXHRCorsCapable()){case 1:return new A(b,c.XHRLocalObject);case 2:return new A(b,c.XDRObject);case 3:return new H(b);default:return new I}};(x["w-iframe-info-receiver"]=function(b,a,e){(new A(e,c.XHRLocalObject)).onfinish=function(a,e){b._didMessage("m"+JSON.stringify([a,e]));b._didClose()}}).prototype.doCleanup=function(){};b=m["iframe-eventsource"]=function(){this.protocol="w-iframe-eventsource";this.i_constructor.apply(this,arguments)};b.prototype=new w;b.enabled=function(){return"EventSource"in
d&&w.enabled()};b.need_body=!0;b.roundTrips=3;(x["w-iframe-eventsource"]=function(b,a){this.run(b,a,"/eventsource",F,c.XHRLocalObject)}).prototype=new p;b=m["iframe-xhr-polling"]=function(){this.protocol="w-iframe-xhr-polling";this.i_constructor.apply(this,arguments)};b.prototype=new w;b.enabled=function(){return d.XMLHttpRequest&&w.enabled()};b.need_body=!0;b.roundTrips=3;(x["w-iframe-xhr-polling"]=function(b,a){this.run(b,a,"/xhr",y,c.XHRLocalObject)}).prototype=new p;b=m["iframe-htmlfile"]=function(){this.protocol=
"w-iframe-htmlfile";this.i_constructor.apply(this,arguments)};b.prototype=new w;b.enabled=function(){return w.enabled()};b.need_body=!0;b.roundTrips=3;(x["w-iframe-htmlfile"]=function(b,a){this.run(b,a,"/htmlfile",G,c.XHRLocalObject)}).prototype=new p;var C=function(b,a,e,c){this.ri=b;this.Receiver=a;this.recv_url=e;this.AjaxObject=c;this._scheduleRecv()};C.prototype._scheduleRecv=function(){var b=this,a=b.poll=new b.Receiver(b.recv_url,b.AjaxObject);a.onmessage=function(a){b.ri._didMessage(a.data)};
a.onclose=function(e){b.poll=a=a.onmessage=a.onclose=null;b.poll_is_closing||("permanent"===e.reason?b.ri._didClose(1006,"Polling error ("+e.reason+")"):b._scheduleRecv())}};C.prototype.abort=function(){this.poll_is_closing=!0;this.poll&&this.poll.abort()};var F=function(b){var a=this,e=new EventSource(b);e.onmessage=function(b){a.dispatchEvent(new g("message",{data:unescape(b.data)}))};a.es_close=e.onerror=function(b,d){var h=d?"user":2!==e.readyState?"network":"permanent";a.es_close=e.onmessage=
e.onerror=null;e.close();e=null;c.delay(200,function(){a.dispatchEvent(new g("close",{reason:h}))})}};F.prototype=new f;F.prototype.abort=function(){this.es_close&&this.es_close({},!0)};var B,G=function(b){var a=this;c.polluteGlobalNamespace();a.id="a"+c.random_string(6,26);b+=(-1===b.indexOf("?")?"?":"&")+"c="+escape("_jp."+a.id);if(void 0===B)if("ActiveXObject"in d)try{B=!!new ActiveXObject("htmlfile")}catch(e){}else B=!1;var h=B?c.createHtmlfile:c.createIframe,f;d._jp[a.id]={start:function(){f.loaded()},
message:function(b){a.dispatchEvent(new g("message",{data:b}))},stop:function(){a.iframe_close({},"network")}};a.iframe_close=function(b,e){f.cleanup();a.iframe_close=f=null;delete d._jp[a.id];a.dispatchEvent(new g("close",{reason:e}))};f=h(b,function(){a.iframe_close({},"permanent")})};G.prototype=new f;G.prototype.abort=function(){this.iframe_close&&this.iframe_close({},"user")};var y=function(b,a){var e=this,c=0;e.xo=new a("POST",b,null);e.xo.onchunk=function(b,a){if(200===b)for(;;){var d=a.slice(c),
h=d.indexOf("\n");if(-1===h)break;c+=h+1;d=d.slice(0,h);e.dispatchEvent(new g("message",{data:d}))}};e.xo.onfinish=function(b,a){e.xo.onchunk(b,a);e.xo=null;e.dispatchEvent(new g("close",{reason:200===b?"network":"permanent"}))}};y.prototype=new f;y.prototype.abort=function(){this.xo&&(this.xo.close(),this.dispatchEvent(new g("close",{reason:"user"})),this.xo=null)};m.getUtils=function(){return c};m.getIframeTransport=function(){return w};return m}();
"_sockjs_onload"in window&&setTimeout(_sockjs_onload,1);"function"===typeof define&&define.amd&&define("sockjs",[],function(){return SockJS});(function(){var a=function(b,a){return function(){return b.apply(a,arguments)}},d=Object.prototype.hasOwnProperty,c=Array.prototype.indexOf||function(b){for(var a=0,c=this.length;a<c;a++)if(a in this&&this[a]===b)return a;return-1},f=function(b,e,c){this.s=b;this.name=e;this._check_pending=a(this._check_pending,this);this.pending=a(this.pending,this);this.on_changes=a(this.on_changes,this);this.retrieve_changes=a(this.retrieve_changes,this);this._send_changes=a(this._send_changes,this);this._queue_change=
a(this._queue_change,this);this._make_change=a(this._make_change,this);this.update=a(this.update,this);this._check_update=a(this._check_update,this);this._notify_client=a(this._notify_client,this);this._index_loaded=a(this._index_loaded,this);this.on_entity_version=a(this.on_entity_version,this);this.get_version=a(this.get_version,this);this.load_versions=a(this.load_versions,this);this.on_index_error=a(this.on_index_error,this);this.on_index_page=a(this.on_index_page,this);this._refresh_store=a(this._refresh_store,
this);this.send=a(this.send,this);this.on_data=a(this.on_data,this);this.start=a(this.start,this);this._remove_entity=a(this._remove_entity,this);this._save_entity=a(this._save_entity,this);this._load_data=a(this._load_data,this);this._verify=a(this._verify,this);this._load_meta=a(this._load_meta,this);this.show_data=a(this.show_data,this);this.on=a(this.on,this);this.jd=this.s.jd;this.options=this.jd.deepCopy(this.s.options);for(e in c)d.call(c,e)&&(b=c[e],this.options[e]=b);this.chan=this.options.n;
this.space=""+this.options.app_id+"/"+this.name;this.username=this.options.username;this.namespace=""+this.username+":"+this.space;this.clientid=null;try{this.clientid=localStorage.getItem(""+this.namespace+"/clientid")}catch(f){this.clientid=null}if(null==this.clientid||0!==this.clientid.indexOf("sjs")){this.clientid="sjs-"+this.s.bversion+"-"+this.uuid(5);try{localStorage.setItem(""+this.namespace+"/clientid")}catch(g){}}this.cb_events="notify notify_init notify_version local get ready notify_pending error".split(" ");
this.cbs={};this.cb_e=this.cb_l=this.cb_ni=this.cb_np=null;this.cb_n=this.cb_nv=this.cb_r=function(){};this.authorized=this.initialized=!1;this.data={last_cv:0,ccid:this.uuid(),store:{},send_queue:[],send_queue_timer:null};this.started=!1;"nostore"in this.options?this.loaded=0:(this._load_meta(),this.loaded=this._load_data());this._last_pending=null;this._send_backoff=15E3;this._backoff_max=12E4;this._backoff_min=15E3};f.prototype.S4=function(){return(65536*(1+Math.random())|0).toString(16).substring(1)};
f.prototype.uuid=function(b){var a,b=b||8;for(a=this.S4();b-=1;)a+=this.S4();return a};f.prototype.now=function(){return(new Date).getTime()};f.prototype.on=function(b,a){if(0<=c.call(this.cb_events,b))switch(this.cbs[b]=a,b){case "get":case "local":return this.cb_l=a;case "notify":return this.cb_n=a;case "notify_version":return this.cb_nv=a;case "notify_pending":return this.cb_np=a;case "notify_init":return this.cb_ni=a;case "ready":return this.cb_r=a;case "error":return this.cb_e=a}else throw Error("unsupported callback event");
};f.prototype.show_data=function(){var b;if(this.s.supports_html5_storage()){for(b in localStorage)d.call(localStorage,b);return!1}};f.prototype._save_meta=function(){if(!this.s.supports_html5_storage())return!1;try{localStorage.setItem(""+this.namespace+"/ccid",this.data.ccid),localStorage.setItem(""+this.namespace+"/last_cv",this.data.last_cv)}catch(b){return!1}return!0};f.prototype._load_meta=function(){var b;if(this.s.supports_html5_storage()){this.data.ccid=localStorage.getItem(""+this.namespace+
"/ccid");if(null==(b=this.data).ccid)b.ccid=1;this.data.last_cv=localStorage.getItem(""+this.namespace+"/last_cv");if(null==(b=this.data).last_cv)b.last_cv=0;return!1}};f.prototype._verify=function(b){if(!("object"in b)||!("version"in b))return!1;if(0===this.jd.entries(b.object)){if(!(0<this.jd.entries(b.last)))return!1}else if(null==b.version)return!1;return!0};f.prototype._load_data=function(){var b,a,c,d,f,g,l,n;if(this.s.supports_html5_storage()){l=""+this.namespace+"/e/";g=l.length;f=0;if(0===
localStorage.length)return 0;a=0;for(n=localStorage.length-1;0<=n?a<=n:a>=n;0<=n?a++:a--)if(d=localStorage.key(a),null!=d&&d.substr(0,g)===l){c=d.substr(g,d.length-g);try{b=JSON.parse(localStorage.getItem(d))}catch(r){b=null}null!=b&&(this._verify(b)?(b.check=null,this.data.store[c]=b,f+=1):this._remove_entity(c))}return f}};f.prototype._save_entity=function(b){var a,c;if(!this.s.supports_html5_storage())return!1;c=""+this.namespace+"/e/"+b;b=this.data.store[b];a=JSON.stringify(b);try{localStorage.setItem(c,
a)}catch(d){return!1}c=JSON.parse(localStorage.getItem(c));return this.jd.equals(b,c)?!0:!1};f.prototype._remove_entity=function(b){if(!this.s.supports_html5_storage())return!1;b=""+this.namespace+"/e/"+b;try{localStorage.removeItem(b)}catch(a){return!1}return!0};f.prototype.start=function(){var b,a;this.namespace=""+this.username+":"+this.space;this.started=!0;this.first=!1;if(this.authorized){if(this.initialized)return this.retrieve_changes();if(!this.first)return this.notify_index={},this._refresh_store()}else this.s.connected&&
(this.first=!0,b="limit"in this.options?"i:1:::"+this.options.limit:"i:1:::40",this.irequest_time=this.now(),this.index_request=!0,this.notify_index={},a={app_id:this.options.app_id,token:this.options.token,name:this.name,clientid:this.clientid,build:this.s.bversion},this.initialized||(a.cmd=b),this.send("init:"+JSON.stringify(a)))};f.prototype.on_data=function(b){var a,c,d,f=this;if("auth:"===b.substr(0,5))if(a=b.substr(5),"expired"===a)this.started=!1,null!=this.cb_e&&this.cb_e("auth");else{if(this.username=
a,this.authorized=!0,this.initialized)return this.start()}else{if("cv:?"===b.substr(0,4))return setTimeout(function(){return f._refresh_store()});if("c:"===b.substr(0,2))return a=JSON.parse(b.substr(2)),"0"===this.data.last_cv&&(0===a.length&&!this.cv_check)&&(this.cv_check=!0,this._refresh_store()),this.on_changes(a);if("i:"===b.substr(0,2))return this.on_index_page(JSON.parse(b.substr(2)));if("e:"===b.substr(0,2)){d=b.indexOf("\n");c=b.substr(2,d-2);a=c.substr(c.lastIndexOf(".")+1);c=c.substr(0,
c.lastIndexOf("."));b=b.substr(d+1);if("?"===b)return this.on_entity_version(null,c,a);b=JSON.parse(b);return this.on_entity_version(b.data,c,a)}return!1}};f.prototype.send=function(b){return this.s.send(""+this.chan+":"+b)};f.prototype._refresh_store=function(){this.send("limit"in this.options?"i:1:::"+this.options.limit:"i:1:::40");this.irequest_time=this.now();this.index_request=!0};f.prototype.on_index_page=function(b){var a,c,d,f,g,l,n,r=this;this.now();c=0;n=b.index;g=0;for(l=n.length;g<l;g++)a=
n[g],this.notify_index[a.id]=!1,c++,setTimeout(function(b){return function(){return r.on_entity_version(b.d,b.id,b.v)}}(a));if(!("mark"in b)||"limit"in this.options){if(this.index_request=!1,"current"in b?(this.data.last_cv=b.current,this._save_meta()):this.data.last_cv=0,0===c)return this._index_loaded()}else return this.index_request=!0,d=b.mark,f=function(b){r.send("i:1:"+b+"::100");return r.irequest_time=r.now()},setTimeout(function(){return f(d)},this.options.page_delay)};f.prototype.on_index_error=
function(){return!1};f.prototype.load_versions=function(b,a){var c,d,f,g;if(!(b in this.data.store))return!1;c=Math.max(this.data.store[b].version-(a+1),1);g=[];d=c;for(f=this.data.store[b].version-1;c<=f?d<=f:d>=f;c<=f?d++:d--)g.push(this.send("e:"+b+"."+d));return g};f.prototype.get_version=function(b,a){return this.send("e:"+(""+b+"."+a))};f.prototype.on_entity_version=function(b,a,c){var f,g,k;f=null!=b?this.jd.deepCopy(b):null;k=!1===this.initialized&&null!=this.cb_ni?this.cb_ni:this.cb_n;if(a in
this.data.store&&"last"in this.data.store[a]&&this.jd.entries(this.data.store[a].last))return f=this.jd.deepCopy(this.data.store[a].last),k(a,f,null),this.notify_index[a]=!0,this._check_update(a);if(a in this.data.store&&c<this.data.store[a].version)return this.cb_nv(a,f,c);a in this.data.store||(this.data.store[a]={});this.data.store[a].id=a;this.data.store[a].object=b;this.data.store[a].version=parseInt(c);k(a,f,c);this.notify_index[a]=!0;b=0;a=this.notify_index;for(g in a)d.call(a,g)&&!1===this.notify_index[g]&&
b++;if(0===b&&!1===this.index_request)return this._index_loaded()};f.prototype._index_loaded=function(){!1===this.initialized&&this.cb_r();this.initialized=!0;return this.retrieve_changes()};f.prototype._notify_client=function(b,a,c,d,f){var g,l,n,r,s;if(null==this.cb_l)this.cb_n(b,a,f);else{g=this.cb_l(b);l=null;s=[];if("array"===this.jd.typeOf(g)&&(n=g[2],r=g[1],g=g[0],l=this.s._captureCursor(n)))s[0]=l.startOffset,"endOffset"in l&&(s[1]=l.endOffset);return null!=g&&null!=c?(g=this.jd.object_diff(c,
g),0===this.jd.entries(g)?a=c:d=this.jd.transform_object_diff(g,d,c),l?(a=this.jd.apply_object_diff_with_offsets(a,d,r,s),null!=n&&"value"in n&&(n.value=a[r]),l.startOffset=s[0],1<s.length&&(l.endOffset=s[1],l.startOffset>=l.endOffset&&(l.collapsed=!0)),this.s._restoreCursor(n,l)):a=this.jd.apply_object_diff(a,d),this.cb_n(b,a,f)):a?this.cb_n(b,a,f):this.cb_n(b,null,null)}};f.prototype._check_update=function(b){var a,c,d,f,g;if(!(b in this.data.store))return!1;c=this.data.store[b];if(c.change){b=
!1;g=this.data.send_queue;d=0;for(f=g.length;d<f;d++)a=g[d],a.id===c.change.id&&a.ccid===c.change.ccid&&(b=!0);return!b?(this._queue_change(c.change),!0):!1}if(null!=c.check)return!1;if(null!=c.last&&0<this.jd.entries(c.last)&&this.jd.equals(c.object,c.last))return c.last=null,this._remove_entity(b),!1;a=this._make_change(b);null!=a?(c.change=a,this._queue_change(a)):this._remove_entity(b);return!0};f.prototype.update=function(b,a){var c,d,f,g,l,n=this;if(1===arguments.length)if(null!=this.cb_l)a=
this.cb_l(b),"array"===this.jd.typeOf(a)&&(a=a[0]);else throw Error("missing 'local' callback");if(null==b&&null==a)return!1;if(null!=b){if(0===b.length||-1!==b.indexOf("/"))return!1}else b=this.uuid();b in this.data.store||(this.data.store[b]={id:b,object:{},version:null,change:null,check:null});d=this.data.store[b];d.last=this.jd.deepCopy(a);d.modified=this.s._time();this._save_entity(b);l=this.data.send_queue;f=0;for(g=l.length;f<g;f++)if(c=l[f],String(b)===c.id)return null;null!=d.check&&clearTimeout(d.check);
var r=b;d.check=setTimeout(function(){d.check=null;d.change=n._make_change(r);d.last=null;n._save_entity(r);return n._queue_change(d.change)},this.options.update_delay);return b};f.prototype._make_change=function(b){var a,c;c=this.data.store[b];a={id:String(b),ccid:this.uuid()};if(this.initialized)if(null!=this.cb_l)b=this.cb_l(b),"array"===this.jd.typeOf(b)&&(b=b[0]);else if(null!=c.last)b=c.last;else return null;else if(null!=c.last)b=c.last;else return null;null!=c.version&&(a.sv=c.version);null===
b&&null!=c.version?a.o="-":null!=b&&null!=c.object?(a.o="M","sendfull"in c?(a.d=this.jd.deepCopy(b),delete c.sendfull):(a.v=this.jd.object_diff(c.object,b),0===this.jd.entries(a.v)&&(a=null))):a=null;return a};f.prototype._queue_change=function(b){if(null!=b)return this.data.send_queue.push(b),this.send("c:"+JSON.stringify(b)),this._check_pending(),null!=this.data.send_queue_timer&&clearTimeout(this.data.send_queue_timer),this.data.send_queue_timer=setTimeout(this._send_changes,this._send_backoff)};
f.prototype._send_changes=function(){var b,a,c,d;if(0===this.data.send_queue.length)this.data.send_queue_timer=null;else{if(this.s.connected){d=this.data.send_queue;a=0;for(c=d.length;a<c;a++)b=d[a],this.send("c:"+JSON.stringify(b))}this._send_backoff*=2;this._send_backoff>this._backoff_max&&(this._send_backoff=this._backoff_max);return this.data.send_queue_timer=setTimeout(this._send_changes,this._send_backoff)}};f.prototype.retrieve_changes=function(){this.send("cv:"+this.data.last_cv)};f.prototype.on_changes=
function(b){var a,c,d,f,g,l,n,r,s,p,m,q=this;c=[];n=!1;this._send_backoff=this._backoff_min;r=0;for(p=b.length;r<p;r++){a=b[r];d=a.id;f=[];m=this.data.send_queue;l=0;for(s=m.length;l<s;l++)g=m[l],a.clientid===this.clientid&&d===g.id&&(a.local=!0,f.push(g),c.push(d));s=0;for(m=f.length;s<m;s++){l=f[s];this.data.store[l.id].change=null;this._save_entity(l.id);for(var u=this.data,v=void 0,t=void 0,z=void 0,w=void 0,z=this.data.send_queue,w=[],v=0,t=z.length;v<t;v++)g=z[v],g!==l&&w.push(g);u.send_queue=
w}0<f.length&&this._check_pending();if("error"in a)switch(a.error){case 412:d=c.indexOf(a.id);-1<d&&c.splice(d,1);break;case 409:break;case 405:a.id in this.data.store&&(this.data.store[a.id].version=null);n=!0;break;case 440:this.data.store[d].sendfull=!0;break;default:a.id in this.data.store&&(this.data.store[a.id].version=null),n=!0}else f=a.o,"-"===f?(delete this.data.store[d],this._remove_entity(d),"local"in a||this._notify_client(a.id,null,null,null,null)):"M"===f&&(f=this.data.store[d],"sv"in
a&&null!=f&&null!=f.version&&f.version===a.sv||!("sv"in a)||1===a.ev?(null==f&&(this.data.store[d]={id:d,object:{},version:null,last:null,change:null,check:null},f=this.data.store[d]),d=this.jd.deepCopy(f.object),f.object=this.jd.apply_object_diff(f.object,a.v),f.version=a.ev,f=this.jd.deepCopy(f.object),"local"in a||this._notify_client(a.id,f,d,a.v,a.ev)):null!=f&&null!=f.version&&a.ev<=f.version||(null!=f&&(this.data.store[d].version=null),n=!0)),n||(this.data.last_cv=a.cv,this._save_meta())}if(n)setTimeout(function(){return q._refresh_store()});
else{b=function(b){return setTimeout(function(){return q._check_update(b)},q.options.update_delay)};n=0;for(r=c.length;n<r;n++)d=c[n],b(d)}};f.prototype.pending=function(){var b,a,c,d,f;d=this.data.send_queue;f=[];a=0;for(c=d.length;a<c;a++)b=d[a],f.push(b.id);d=this.data.send_queue;f=[];a=0;for(c=d.length;a<c;a++)b=d[a],f.push(b.id);return f};f.prototype._check_pending=function(){var b,a,c,d,f,g;if(null!=this.cb_np){b=this.pending();a=!0;if(this._last_pending)if(a=!1,this._last_pending.length===
b.length){g=this._last_pending;d=0;for(f=g.length;d<f;d++)c=g[d],-1===b.indexOf(c)&&(a=!0)}else a=!0;if(a)return this._last_pending=b,this.cb_np(b)}};var g=function(b,c){var f,g,j;this.app_id=b;this.options=c;this._restoreCursor=a(this._restoreCursor,this);this._captureCursor=a(this._captureCursor,this);this._sock_message=a(this._sock_message,this);this._sock_hb_check=a(this._sock_hb_check,this);this._sock_closed=a(this._sock_closed,this);this._sock_opened=a(this._sock_opened,this);this._sock_connect=
a(this._sock_connect,this);this.synced=a(this.synced,this);this.send=a(this.send,this);this.stop=a(this.stop,this);this.start=a(this.start,this);this.on=a(this.on,this);this.bucket=a(this.bucket,this);this.bversion=2012121301;this.jd=new jsondiff;this.dmp=jsondiff.dmp;this.auth_token=null;this.options=this.options||{};this.options.app_id=this.app_id;this.sock_opts={debug:!1};if("sockjs"in this.options)for(f in j=this.options.sockjs,j)d.call(j,f)&&(g=j[f],this.sock_opts[f]=g);"host"in this.options||
(this.options.host="api.simperium.com");"port"in this.options||(this.options.port=80);"token"in this.options&&(this.auth_token=this.options.token);f=-1!==this.options.host.indexOf("simperium.com")?"https":"http";this.buckets={};this.channels=0;"update_delay"in this.options||(this.options.update_delay=0);"page_delay"in this.options||(this.options.page_delay=0);this.options.prefix="sock";this.options.port=parseInt(this.options.port);this.sock_url=80!==this.options.port&&443!==this.options.port?""+f+
"://"+this.options.host+":"+this.options.port+"/"+this.options.prefix:""+f+"://"+this.options.host+"/"+this.options.prefix;this.stopped=!1;this._sock_backoff=3E3;this._sock_hb=1;this._sock_connect()};g.prototype.lowerstrip=function(b){b=b.toLowerCase();return null!=String.prototype.trim?b.trim():b.replace(/^\s+|\s+$/g,"")};g.prototype._time=function(){var b;b=new Date;return Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes(),b.getUTCSeconds(),b.getUTCMilliseconds())/
1E3};g.prototype.supports_html5_storage=function(){try{return"localStorage"in window&&null!==window.localStorage}catch(b){return!1}};g.prototype.bucket=function(b,a){var c,b=this.lowerstrip(b),a=a||{};a.n=this.channels++;c=new f(this,b,a);return this.buckets[a.n]=c};g.prototype.on=function(b,a,c){return this.buckets[b].on(a,c)};g.prototype.start=function(){var b,a,c,f;this.stopped=!1;c=this.buckets;f=[];for(a in c)d.call(c,a)&&(b=c[a],f.push(b.start()));return f};g.prototype.stop=function(){this.stopped=
!0;if(null!=this.sock)return this.sock.close()};g.prototype.send=function(b){return this.sock.send(b)};g.prototype.synced=function(){var b,a,c;c=this.buckets;for(a in c)if(d.call(c,a)&&(b=c[a],0<b.pending().length))return!1;return!0};g.prototype._sock_connect=function(){this.authorized=this.connected=!1;this.sock=new SockJS(this.sock_url,void 0,this.sock_opts);this.sock.onopen=this._sock_opened;this.sock.onmessage=this._sock_message;return this.sock.onclose=this._sock_closed};g.prototype._sock_opened=
function(){var b,a,c,f;this._sock_backoff=3E3;this.connected=!0;this._sock_hb_timer=setTimeout(this._sock_hb_check,2E4);c=this.buckets;f=[];for(a in c)d.call(c,a)&&(b=c[a],b.started?f.push(b.start()):f.push(void 0));return f};g.prototype._sock_closed=function(){var b,a,c;this.connected=!1;c=this.buckets;for(a in c)d.call(c,a)&&(b=c[a],b.authorized=!1);this._sock_backoff=4E3>this._sock_backoff?this._sock_backoff+1:15E3;this._sock_hb_timer&&(clearTimeout(this._sock_hb_timer),this._sock_hb_timer=null);
if(!this.stopped)return setTimeout(this._sock_connect,this._sock_backoff)};g.prototype._sock_hb_check=function(){var b;b=(new Date).getTime()-this._sock_msg_time;if(!1!==this.connected)return 4E4<b?this.sock.close():15E3<b&&this.sock.send("h:"+this._sock_hb),this._sock_hb_timer=setTimeout(this._sock_hb_check,2E4)};g.prototype._sock_message=function(b){var a,c;this._sock_msg_time=(new Date).getTime();a=b.data;c=a.indexOf(":");b=null;if(1===c&&"h"===a.charAt(0))this._sock_hb=a.substr(2);else{try{b=
parseInt(a.substr(0,c)),a=a.substr(c+1)}catch(d){b=null}if(null!==b&&b in this.buckets)return this.buckets[b].on_data(a)}};g.prototype._captureCursor=function(){};g.prototype._captureCursor=function(b){if("activeElement"in b&&!b.activeElement)return null;var a=this.dmp.Match_MaxBits/2,c=b.value,d={};if("selectionStart"in b){try{var f=b.selectionStart,g=b.selectionEnd}catch(l){return null}d.startPrefix=c.substring(f-a,f);d.startSuffix=c.substring(f,f+a);d.startOffset=f;d.collapsed=f==g;d.collapsed||
(d.endPrefix=c.substring(g-a,g),d.endSuffix=c.substring(g,g+a),d.endOffset=g)}else{for(f=b;f.parentNode;)f=f.parentNode;if(!f.selection||!f.selection.createRange)return null;c=f.selection.createRange();if(c.parentElement()!=b)return null;f=f.body.createTextRange();d.collapsed=""==c.text;f.moveToElementText(b);d.collapsed||(f.setEndPoint("EndToEnd",c),d.endPrefix=f.text,d.endOffset=d.endPrefix.length,d.endPrefix=d.endPrefix.substring(d.endPrefix.length-a));f.setEndPoint("EndToStart",c);d.startPrefix=
f.text;d.startOffset=d.startPrefix.length;d.startPrefix=d.startPrefix.substring(d.startPrefix.length-a);f.moveToElementText(b);f.setEndPoint("StartToStart",c);d.startSuffix=f.text.substring(0,a);d.collapsed||(f.setEndPoint("StartToEnd",c),d.endSuffix=f.text.substring(0,a))}"scrollTop"in b&&(d.scrollTop=b.scrollTop/b.scrollHeight,d.scrollLeft=b.scrollLeft/b.scrollWidth);return d};g.prototype._restoreCursor=function(){};g.prototype._restoreCursor=function(b,a){this.dmp.Match_Distance=1E3;this.dmp.Match_Threshold=
0.9;var c=this.dmp.Match_MaxBits/2,d=b.value,f=a.startPrefix+a.startSuffix,g,l=this.dmp.match_main(d,f,a.startOffset-c);null!==l&&(g=d.substring(l,l+f.length),f=this.dmp.diff_main(f,g,!1),l+=this.dmp.diff_xIndex(f,a.startPrefix.length));var n=null;a.collapsed||(f=a.endPrefix+a.endSuffix,n=this.dmp.match_main(d,f,a.endOffset-c),null!==n&&(g=d.substring(n,n+f.length),f=this.dmp.diff_main(f,g,!1),n+=this.dmp.diff_xIndex(f,a.endPrefix.length)));null===l&&null!==n?l=n:null===l&&null===n&&(l=a.startOffset);
null===n&&(n=l);if("selectionStart"in b)b.selectionStart=l,b.selectionEnd=n;else{for(c=b;c.parentNode;)c=c.parentNode;if(!c.selection||!c.selection.createRange)return;d=b.value.substring(0,l);d=d.replace(/\r\n/g,"\n").length;c=c.body.createTextRange();c.moveToElementText(b);c.collapse(!0);c.moveStart("character",d);a.collapsed||(d=b.value.substring(l,n),l=d.replace(/\r\n/g,"\n").length,c.moveEnd("character",l));c.select()}"scrollTop"in a&&(b.scrollTop=a.scrollTop*b.scrollHeight,b.scrollLeft=a.scrollLeft*
b.scrollWidth)};window.Simperium=g;f.prototype.on=f.prototype.on;f.prototype.start=f.prototype.start;f.prototype.load_versions=f.prototype.load_versions;f.prototype.pending=f.prototype.pending;g.prototype.on=g.prototype.on;g.prototype.start=g.prototype.start;g.prototype.bucket=g.prototype.bucket;g.prototype.synced=g.prototype.synced}).call(this);
